// FRENCH MASTERY - VERB DATABASE with 150+ verbs

// Helper to generate regular -ER verb conjugations
function generateERVerb(infinitive, translation) {
    const stem = infinitive.slice(0, -2);
    const pp = stem + "é";
    return {
        infinitive, translation, group: "er", auxiliary: "avoir",
        pastParticiple: pp, presentParticiple: stem + "ant",
        conjugations: {
            present: { je: stem + "e", tu: stem + "es", il: stem + "e", nous: stem + "ons", vous: stem + "ez", ils: stem + "ent" },
            imperfect: { je: stem + "ais", tu: stem + "ais", il: stem + "ait", nous: stem + "ions", vous: stem + "iez", ils: stem + "aient" },
            future: { je: infinitive + "ai", tu: infinitive + "as", il: infinitive + "a", nous: infinitive + "ons", vous: infinitive + "ez", ils: infinitive + "ont" },
            conditional: { je: infinitive + "ais", tu: infinitive + "ais", il: infinitive + "ait", nous: infinitive + "ions", vous: infinitive + "iez", ils: infinitive + "aient" },
            passé_composé: { je: "ai " + pp, tu: "as " + pp, il: "a " + pp, nous: "avons " + pp, vous: "avez " + pp, ils: "ont " + pp },
            subjonctif_present: { je: stem + "e", tu: stem + "es", il: stem + "e", nous: stem + "ions", vous: stem + "iez", ils: stem + "ent" },
            imperative: { tu: stem + "e", nous: stem + "ons", vous: stem + "ez" }
        }
    };
}

function generateIRVerb(infinitive, translation) {
    const stem = infinitive.slice(0, -2);
    const pp = stem + "i";
    return {
        infinitive, translation, group: "ir", auxiliary: "avoir",
        pastParticiple: pp, presentParticiple: stem + "issant",
        conjugations: {
            present: { je: stem + "is", tu: stem + "is", il: stem + "it", nous: stem + "issons", vous: stem + "issez", ils: stem + "issent" },
            imperfect: { je: stem + "issais", tu: stem + "issais", il: stem + "issait", nous: stem + "issions", vous: stem + "issiez", ils: stem + "issaient" },
            future: { je: infinitive + "ai", tu: infinitive + "as", il: infinitive + "a", nous: infinitive + "ons", vous: infinitive + "ez", ils: infinitive + "ont" },
            conditional: { je: infinitive + "ais", tu: infinitive + "ais", il: infinitive + "ait", nous: infinitive + "ions", vous: infinitive + "iez", ils: infinitive + "aient" },
            passé_composé: { je: "ai " + pp, tu: "as " + pp, il: "a " + pp, nous: "avons " + pp, vous: "avez " + pp, ils: "ont " + pp },
            subjonctif_present: { je: stem + "isse", tu: stem + "isses", il: stem + "isse", nous: stem + "issions", vous: stem + "issiez", ils: stem + "issent" },
            imperative: { tu: stem + "is", nous: stem + "issons", vous: stem + "issez" }
        }
    };
}

function generateREVerb(infinitive, translation) {
    const stem = infinitive.slice(0, -2);
    const pp = stem + "u";
    return {
        infinitive, translation, group: "re", auxiliary: "avoir",
        pastParticiple: pp, presentParticiple: stem + "ant",
        conjugations: {
            present: { je: stem + "s", tu: stem + "s", il: stem, nous: stem + "ons", vous: stem + "ez", ils: stem + "ent" },
            imperfect: { je: stem + "ais", tu: stem + "ais", il: stem + "ait", nous: stem + "ions", vous: stem + "iez", ils: stem + "aient" },
            future: { je: stem + "rai", tu: stem + "ras", il: stem + "ra", nous: stem + "rons", vous: stem + "rez", ils: stem + "ront" },
            conditional: { je: stem + "rais", tu: stem + "rais", il: stem + "rait", nous: stem + "rions", vous: stem + "riez", ils: stem + "raient" },
            passé_composé: { je: "ai " + pp, tu: "as " + pp, il: "a " + pp, nous: "avons " + pp, vous: "avez " + pp, ils: "ont " + pp },
            subjonctif_present: { je: stem + "e", tu: stem + "es", il: stem + "e", nous: stem + "ions", vous: stem + "iez", ils: stem + "ent" },
            imperative: { tu: stem + "s", nous: stem + "ons", vous: stem + "ez" }
        }
    };
}

const FRENCH_VERBS = [
    // ESSENTIAL IRREGULAR VERBS
    { infinitive: "être", translation: "to be", group: "irregular", auxiliary: "avoir", pastParticiple: "été", presentParticiple: "étant",
      conjugations: { present: { je: "suis", tu: "es", il: "est", nous: "sommes", vous: "êtes", ils: "sont" },
        imperfect: { je: "étais", tu: "étais", il: "était", nous: "étions", vous: "étiez", ils: "étaient" },
        future: { je: "serai", tu: "seras", il: "sera", nous: "serons", vous: "serez", ils: "seront" },
        conditional: { je: "serais", tu: "serais", il: "serait", nous: "serions", vous: "seriez", ils: "seraient" },
        passé_composé: { je: "ai été", tu: "as été", il: "a été", nous: "avons été", vous: "avez été", ils: "ont été" },
        subjonctif_present: { je: "sois", tu: "sois", il: "soit", nous: "soyons", vous: "soyez", ils: "soient" },
        imperative: { tu: "sois", nous: "soyons", vous: "soyez" } } },
    { infinitive: "avoir", translation: "to have", group: "irregular", auxiliary: "avoir", pastParticiple: "eu", presentParticiple: "ayant",
      conjugations: { present: { je: "ai", tu: "as", il: "a", nous: "avons", vous: "avez", ils: "ont" },
        imperfect: { je: "avais", tu: "avais", il: "avait", nous: "avions", vous: "aviez", ils: "avaient" },
        future: { je: "aurai", tu: "auras", il: "aura", nous: "aurons", vous: "aurez", ils: "auront" },
        conditional: { je: "aurais", tu: "aurais", il: "aurait", nous: "aurions", vous: "auriez", ils: "auraient" },
        passé_composé: { je: "ai eu", tu: "as eu", il: "a eu", nous: "avons eu", vous: "avez eu", ils: "ont eu" },
        subjonctif_present: { je: "aie", tu: "aies", il: "ait", nous: "ayons", vous: "ayez", ils: "aient" },
        imperative: { tu: "aie", nous: "ayons", vous: "ayez" } } },
    { infinitive: "aller", translation: "to go", group: "irregular", auxiliary: "être", pastParticiple: "allé", presentParticiple: "allant",
      conjugations: { present: { je: "vais", tu: "vas", il: "va", nous: "allons", vous: "allez", ils: "vont" },
        imperfect: { je: "allais", tu: "allais", il: "allait", nous: "allions", vous: "alliez", ils: "allaient" },
        future: { je: "irai", tu: "iras", il: "ira", nous: "irons", vous: "irez", ils: "iront" },
        conditional: { je: "irais", tu: "irais", il: "irait", nous: "irions", vous: "iriez", ils: "iraient" },
        passé_composé: { je: "suis allé(e)", tu: "es allé(e)", il: "est allé", nous: "sommes allé(e)s", vous: "êtes allé(e)(s)", ils: "sont allés" },
        subjonctif_present: { je: "aille", tu: "ailles", il: "aille", nous: "allions", vous: "alliez", ils: "aillent" },
        imperative: { tu: "va", nous: "allons", vous: "allez" } } },
    { infinitive: "faire", translation: "to do/make", group: "irregular", auxiliary: "avoir", pastParticiple: "fait", presentParticiple: "faisant",
      conjugations: { present: { je: "fais", tu: "fais", il: "fait", nous: "faisons", vous: "faites", ils: "font" },
        imperfect: { je: "faisais", tu: "faisais", il: "faisait", nous: "faisions", vous: "faisiez", ils: "faisaient" },
        future: { je: "ferai", tu: "feras", il: "fera", nous: "ferons", vous: "ferez", ils: "feront" },
        conditional: { je: "ferais", tu: "ferais", il: "ferait", nous: "ferions", vous: "feriez", ils: "feraient" },
        passé_composé: { je: "ai fait", tu: "as fait", il: "a fait", nous: "avons fait", vous: "avez fait", ils: "ont fait" },
        subjonctif_present: { je: "fasse", tu: "fasses", il: "fasse", nous: "fassions", vous: "fassiez", ils: "fassent" },
        imperative: { tu: "fais", nous: "faisons", vous: "faites" } } },
    { infinitive: "pouvoir", translation: "can/to be able", group: "irregular", auxiliary: "avoir", pastParticiple: "pu", presentParticiple: "pouvant",
      conjugations: { present: { je: "peux", tu: "peux", il: "peut", nous: "pouvons", vous: "pouvez", ils: "peuvent" },
        imperfect: { je: "pouvais", tu: "pouvais", il: "pouvait", nous: "pouvions", vous: "pouviez", ils: "pouvaient" },
        future: { je: "pourrai", tu: "pourras", il: "pourra", nous: "pourrons", vous: "pourrez", ils: "pourront" },
        conditional: { je: "pourrais", tu: "pourrais", il: "pourrait", nous: "pourrions", vous: "pourriez", ils: "pourraient" },
        passé_composé: { je: "ai pu", tu: "as pu", il: "a pu", nous: "avons pu", vous: "avez pu", ils: "ont pu" },
        subjonctif_present: { je: "puisse", tu: "puisses", il: "puisse", nous: "puissions", vous: "puissiez", ils: "puissent" },
        imperative: { tu: "-", nous: "-", vous: "-" } } },
    { infinitive: "vouloir", translation: "to want", group: "irregular", auxiliary: "avoir", pastParticiple: "voulu", presentParticiple: "voulant",
      conjugations: { present: { je: "veux", tu: "veux", il: "veut", nous: "voulons", vous: "voulez", ils: "veulent" },
        imperfect: { je: "voulais", tu: "voulais", il: "voulait", nous: "voulions", vous: "vouliez", ils: "voulaient" },
        future: { je: "voudrai", tu: "voudras", il: "voudra", nous: "voudrons", vous: "voudrez", ils: "voudront" },
        conditional: { je: "voudrais", tu: "voudrais", il: "voudrait", nous: "voudrions", vous: "voudriez", ils: "voudraient" },
        passé_composé: { je: "ai voulu", tu: "as voulu", il: "a voulu", nous: "avons voulu", vous: "avez voulu", ils: "ont voulu" },
        subjonctif_present: { je: "veuille", tu: "veuilles", il: "veuille", nous: "voulions", vous: "vouliez", ils: "veuillent" },
        imperative: { tu: "veuille", nous: "veuillons", vous: "veuillez" } } },
    { infinitive: "devoir", translation: "must/to have to", group: "irregular", auxiliary: "avoir", pastParticiple: "dû", presentParticiple: "devant",
      conjugations: { present: { je: "dois", tu: "dois", il: "doit", nous: "devons", vous: "devez", ils: "doivent" },
        imperfect: { je: "devais", tu: "devais", il: "devait", nous: "devions", vous: "deviez", ils: "devaient" },
        future: { je: "devrai", tu: "devras", il: "devra", nous: "devrons", vous: "devrez", ils: "devront" },
        conditional: { je: "devrais", tu: "devrais", il: "devrait", nous: "devrions", vous: "devriez", ils: "devraient" },
        passé_composé: { je: "ai dû", tu: "as dû", il: "a dû", nous: "avons dû", vous: "avez dû", ils: "ont dû" },
        subjonctif_present: { je: "doive", tu: "doives", il: "doive", nous: "devions", vous: "deviez", ils: "doivent" },
        imperative: { tu: "dois", nous: "devons", vous: "devez" } } },
    { infinitive: "savoir", translation: "to know (facts)", group: "irregular", auxiliary: "avoir", pastParticiple: "su", presentParticiple: "sachant",
      conjugations: { present: { je: "sais", tu: "sais", il: "sait", nous: "savons", vous: "savez", ils: "savent" },
        imperfect: { je: "savais", tu: "savais", il: "savait", nous: "savions", vous: "saviez", ils: "savaient" },
        future: { je: "saurai", tu: "sauras", il: "saura", nous: "saurons", vous: "saurez", ils: "sauront" },
        conditional: { je: "saurais", tu: "saurais", il: "saurait", nous: "saurions", vous: "sauriez", ils: "sauraient" },
        passé_composé: { je: "ai su", tu: "as su", il: "a su", nous: "avons su", vous: "avez su", ils: "ont su" },
        subjonctif_present: { je: "sache", tu: "saches", il: "sache", nous: "sachions", vous: "sachiez", ils: "sachent" },
        imperative: { tu: "sache", nous: "sachons", vous: "sachez" } } },
    { infinitive: "venir", translation: "to come", group: "irregular", auxiliary: "être", pastParticiple: "venu", presentParticiple: "venant",
      conjugations: { present: { je: "viens", tu: "viens", il: "vient", nous: "venons", vous: "venez", ils: "viennent" },
        imperfect: { je: "venais", tu: "venais", il: "venait", nous: "venions", vous: "veniez", ils: "venaient" },
        future: { je: "viendrai", tu: "viendras", il: "viendra", nous: "viendrons", vous: "viendrez", ils: "viendront" },
        conditional: { je: "viendrais", tu: "viendrais", il: "viendrait", nous: "viendrions", vous: "viendriez", ils: "viendraient" },
        passé_composé: { je: "suis venu(e)", tu: "es venu(e)", il: "est venu", nous: "sommes venu(e)s", vous: "êtes venu(e)(s)", ils: "sont venus" },
        subjonctif_present: { je: "vienne", tu: "viennes", il: "vienne", nous: "venions", vous: "veniez", ils: "viennent" },
        imperative: { tu: "viens", nous: "venons", vous: "venez" } } },
    { infinitive: "voir", translation: "to see", group: "irregular", auxiliary: "avoir", pastParticiple: "vu", presentParticiple: "voyant",
      conjugations: { present: { je: "vois", tu: "vois", il: "voit", nous: "voyons", vous: "voyez", ils: "voient" },
        imperfect: { je: "voyais", tu: "voyais", il: "voyait", nous: "voyions", vous: "voyiez", ils: "voyaient" },
        future: { je: "verrai", tu: "verras", il: "verra", nous: "verrons", vous: "verrez", ils: "verront" },
        conditional: { je: "verrais", tu: "verrais", il: "verrait", nous: "verrions", vous: "verriez", ils: "verraient" },
        passé_composé: { je: "ai vu", tu: "as vu", il: "a vu", nous: "avons vu", vous: "avez vu", ils: "ont vu" },
        subjonctif_present: { je: "voie", tu: "voies", il: "voie", nous: "voyions", vous: "voyiez", ils: "voient" },
        imperative: { tu: "vois", nous: "voyons", vous: "voyez" } } },
    { infinitive: "prendre", translation: "to take", group: "irregular", auxiliary: "avoir", pastParticiple: "pris", presentParticiple: "prenant",
      conjugations: { present: { je: "prends", tu: "prends", il: "prend", nous: "prenons", vous: "prenez", ils: "prennent" },
        imperfect: { je: "prenais", tu: "prenais", il: "prenait", nous: "prenions", vous: "preniez", ils: "prenaient" },
        future: { je: "prendrai", tu: "prendras", il: "prendra", nous: "prendrons", vous: "prendrez", ils: "prendront" },
        conditional: { je: "prendrais", tu: "prendrais", il: "prendrait", nous: "prendrions", vous: "prendriez", ils: "prendraient" },
        passé_composé: { je: "ai pris", tu: "as pris", il: "a pris", nous: "avons pris", vous: "avez pris", ils: "ont pris" },
        subjonctif_present: { je: "prenne", tu: "prennes", il: "prenne", nous: "prenions", vous: "preniez", ils: "prennent" },
        imperative: { tu: "prends", nous: "prenons", vous: "prenez" } } },
    { infinitive: "mettre", translation: "to put", group: "irregular", auxiliary: "avoir", pastParticiple: "mis", presentParticiple: "mettant",
      conjugations: { present: { je: "mets", tu: "mets", il: "met", nous: "mettons", vous: "mettez", ils: "mettent" },
        imperfect: { je: "mettais", tu: "mettais", il: "mettait", nous: "mettions", vous: "mettiez", ils: "mettaient" },
        future: { je: "mettrai", tu: "mettras", il: "mettra", nous: "mettrons", vous: "mettrez", ils: "mettront" },
        conditional: { je: "mettrais", tu: "mettrais", il: "mettrait", nous: "mettrions", vous: "mettriez", ils: "mettraient" },
        passé_composé: { je: "ai mis", tu: "as mis", il: "a mis", nous: "avons mis", vous: "avez mis", ils: "ont mis" },
        subjonctif_present: { je: "mette", tu: "mettes", il: "mette", nous: "mettions", vous: "mettiez", ils: "mettent" },
        imperative: { tu: "mets", nous: "mettons", vous: "mettez" } } },
    { infinitive: "dire", translation: "to say/tell", group: "irregular", auxiliary: "avoir", pastParticiple: "dit", presentParticiple: "disant",
      conjugations: { present: { je: "dis", tu: "dis", il: "dit", nous: "disons", vous: "dites", ils: "disent" },
        imperfect: { je: "disais", tu: "disais", il: "disait", nous: "disions", vous: "disiez", ils: "disaient" },
        future: { je: "dirai", tu: "diras", il: "dira", nous: "dirons", vous: "direz", ils: "diront" },
        conditional: { je: "dirais", tu: "dirais", il: "dirait", nous: "dirions", vous: "diriez", ils: "diraient" },
        passé_composé: { je: "ai dit", tu: "as dit", il: "a dit", nous: "avons dit", vous: "avez dit", ils: "ont dit" },
        subjonctif_present: { je: "dise", tu: "dises", il: "dise", nous: "disions", vous: "disiez", ils: "disent" },
        imperative: { tu: "dis", nous: "disons", vous: "dites" } } },
    { infinitive: "partir", translation: "to leave", group: "irregular", auxiliary: "être", pastParticiple: "parti", presentParticiple: "partant",
      conjugations: { present: { je: "pars", tu: "pars", il: "part", nous: "partons", vous: "partez", ils: "partent" },
        imperfect: { je: "partais", tu: "partais", il: "partait", nous: "partions", vous: "partiez", ils: "partaient" },
        future: { je: "partirai", tu: "partiras", il: "partira", nous: "partirons", vous: "partirez", ils: "partiront" },
        conditional: { je: "partirais", tu: "partirais", il: "partirait", nous: "partirions", vous: "partiriez", ils: "partiraient" },
        passé_composé: { je: "suis parti(e)", tu: "es parti(e)", il: "est parti", nous: "sommes parti(e)s", vous: "êtes parti(e)(s)", ils: "sont partis" },
        subjonctif_present: { je: "parte", tu: "partes", il: "parte", nous: "partions", vous: "partiez", ils: "partent" },
        imperative: { tu: "pars", nous: "partons", vous: "partez" } } },
    { infinitive: "sortir", translation: "to go out", group: "irregular", auxiliary: "être", pastParticiple: "sorti", presentParticiple: "sortant",
      conjugations: { present: { je: "sors", tu: "sors", il: "sort", nous: "sortons", vous: "sortez", ils: "sortent" },
        imperfect: { je: "sortais", tu: "sortais", il: "sortait", nous: "sortions", vous: "sortiez", ils: "sortaient" },
        future: { je: "sortirai", tu: "sortiras", il: "sortira", nous: "sortirons", vous: "sortirez", ils: "sortiront" },
        conditional: { je: "sortirais", tu: "sortirais", il: "sortirait", nous: "sortirions", vous: "sortiriez", ils: "sortiraient" },
        passé_composé: { je: "suis sorti(e)", tu: "es sorti(e)", il: "est sorti", nous: "sommes sorti(e)s", vous: "êtes sorti(e)(s)", ils: "sont sortis" },
        subjonctif_present: { je: "sorte", tu: "sortes", il: "sorte", nous: "sortions", vous: "sortiez", ils: "sortent" },
        imperative: { tu: "sors", nous: "sortons", vous: "sortez" } } },
    { infinitive: "dormir", translation: "to sleep", group: "irregular", auxiliary: "avoir", pastParticiple: "dormi", presentParticiple: "dormant",
      conjugations: { present: { je: "dors", tu: "dors", il: "dort", nous: "dormons", vous: "dormez", ils: "dorment" },
        imperfect: { je: "dormais", tu: "dormais", il: "dormait", nous: "dormions", vous: "dormiez", ils: "dormaient" },
        future: { je: "dormirai", tu: "dormiras", il: "dormira", nous: "dormirons", vous: "dormirez", ils: "dormiront" },
        conditional: { je: "dormirais", tu: "dormirais", il: "dormirait", nous: "dormirions", vous: "dormiriez", ils: "dormiraient" },
        passé_composé: { je: "ai dormi", tu: "as dormi", il: "a dormi", nous: "avons dormi", vous: "avez dormi", ils: "ont dormi" },
        subjonctif_present: { je: "dorme", tu: "dormes", il: "dorme", nous: "dormions", vous: "dormiez", ils: "dorment" },
        imperative: { tu: "dors", nous: "dormons", vous: "dormez" } } },
    { infinitive: "lire", translation: "to read", group: "irregular", auxiliary: "avoir", pastParticiple: "lu", presentParticiple: "lisant",
      conjugations: { present: { je: "lis", tu: "lis", il: "lit", nous: "lisons", vous: "lisez", ils: "lisent" },
        imperfect: { je: "lisais", tu: "lisais", il: "lisait", nous: "lisions", vous: "lisiez", ils: "lisaient" },
        future: { je: "lirai", tu: "liras", il: "lira", nous: "lirons", vous: "lirez", ils: "liront" },
        conditional: { je: "lirais", tu: "lirais", il: "lirait", nous: "lirions", vous: "liriez", ils: "liraient" },
        passé_composé: { je: "ai lu", tu: "as lu", il: "a lu", nous: "avons lu", vous: "avez lu", ils: "ont lu" },
        subjonctif_present: { je: "lise", tu: "lises", il: "lise", nous: "lisions", vous: "lisiez", ils: "lisent" },
        imperative: { tu: "lis", nous: "lisons", vous: "lisez" } } },
    { infinitive: "écrire", translation: "to write", group: "irregular", auxiliary: "avoir", pastParticiple: "écrit", presentParticiple: "écrivant",
      conjugations: { present: { je: "écris", tu: "écris", il: "écrit", nous: "écrivons", vous: "écrivez", ils: "écrivent" },
        imperfect: { je: "écrivais", tu: "écrivais", il: "écrivait", nous: "écrivions", vous: "écriviez", ils: "écrivaient" },
        future: { je: "écrirai", tu: "écriras", il: "écrira", nous: "écrirons", vous: "écrirez", ils: "écriront" },
        conditional: { je: "écrirais", tu: "écrirais", il: "écrirait", nous: "écririons", vous: "écririez", ils: "écriraient" },
        passé_composé: { je: "ai écrit", tu: "as écrit", il: "a écrit", nous: "avons écrit", vous: "avez écrit", ils: "ont écrit" },
        subjonctif_present: { je: "écrive", tu: "écrives", il: "écrive", nous: "écrivions", vous: "écriviez", ils: "écrivent" },
        imperative: { tu: "écris", nous: "écrivons", vous: "écrivez" } } },
    { infinitive: "boire", translation: "to drink", group: "irregular", auxiliary: "avoir", pastParticiple: "bu", presentParticiple: "buvant",
      conjugations: { present: { je: "bois", tu: "bois", il: "boit", nous: "buvons", vous: "buvez", ils: "boivent" },
        imperfect: { je: "buvais", tu: "buvais", il: "buvait", nous: "buvions", vous: "buviez", ils: "buvaient" },
        future: { je: "boirai", tu: "boiras", il: "boira", nous: "boirons", vous: "boirez", ils: "boiront" },
        conditional: { je: "boirais", tu: "boirais", il: "boirait", nous: "boirions", vous: "boiriez", ils: "boiraient" },
        passé_composé: { je: "ai bu", tu: "as bu", il: "a bu", nous: "avons bu", vous: "avez bu", ils: "ont bu" },
        subjonctif_present: { je: "boive", tu: "boives", il: "boive", nous: "buvions", vous: "buviez", ils: "boivent" },
        imperative: { tu: "bois", nous: "buvons", vous: "buvez" } } },
    { infinitive: "connaître", translation: "to know (person)", group: "irregular", auxiliary: "avoir", pastParticiple: "connu", presentParticiple: "connaissant",
      conjugations: { present: { je: "connais", tu: "connais", il: "connaît", nous: "connaissons", vous: "connaissez", ils: "connaissent" },
        imperfect: { je: "connaissais", tu: "connaissais", il: "connaissait", nous: "connaissions", vous: "connaissiez", ils: "connaissaient" },
        future: { je: "connaîtrai", tu: "connaîtras", il: "connaîtra", nous: "connaîtrons", vous: "connaîtrez", ils: "connaîtront" },
        conditional: { je: "connaîtrais", tu: "connaîtrais", il: "connaîtrait", nous: "connaîtrions", vous: "connaîtriez", ils: "connaîtraient" },
        passé_composé: { je: "ai connu", tu: "as connu", il: "a connu", nous: "avons connu", vous: "avez connu", ils: "ont connu" },
        subjonctif_present: { je: "connaisse", tu: "connaisses", il: "connaisse", nous: "connaissions", vous: "connaissiez", ils: "connaissent" },
        imperative: { tu: "connais", nous: "connaissons", vous: "connaissez" } } },
    { infinitive: "croire", translation: "to believe", group: "irregular", auxiliary: "avoir", pastParticiple: "cru", presentParticiple: "croyant",
      conjugations: { present: { je: "crois", tu: "crois", il: "croit", nous: "croyons", vous: "croyez", ils: "croient" },
        imperfect: { je: "croyais", tu: "croyais", il: "croyait", nous: "croyions", vous: "croyiez", ils: "croyaient" },
        future: { je: "croirai", tu: "croiras", il: "croira", nous: "croirons", vous: "croirez", ils: "croiront" },
        conditional: { je: "croirais", tu: "croirais", il: "croirait", nous: "croirions", vous: "croiriez", ils: "croiraient" },
        passé_composé: { je: "ai cru", tu: "as cru", il: "a cru", nous: "avons cru", vous: "avez cru", ils: "ont cru" },
        subjonctif_present: { je: "croie", tu: "croies", il: "croie", nous: "croyions", vous: "croyiez", ils: "croient" },
        imperative: { tu: "crois", nous: "croyons", vous: "croyez" } } },
    { infinitive: "vivre", translation: "to live", group: "irregular", auxiliary: "avoir", pastParticiple: "vécu", presentParticiple: "vivant",
      conjugations: { present: { je: "vis", tu: "vis", il: "vit", nous: "vivons", vous: "vivez", ils: "vivent" },
        imperfect: { je: "vivais", tu: "vivais", il: "vivait", nous: "vivions", vous: "viviez", ils: "vivaient" },
        future: { je: "vivrai", tu: "vivras", il: "vivra", nous: "vivrons", vous: "vivrez", ils: "vivront" },
        conditional: { je: "vivrais", tu: "vivrais", il: "vivrait", nous: "vivrions", vous: "vivriez", ils: "vivraient" },
        passé_composé: { je: "ai vécu", tu: "as vécu", il: "a vécu", nous: "avons vécu", vous: "avez vécu", ils: "ont vécu" },
        subjonctif_present: { je: "vive", tu: "vives", il: "vive", nous: "vivions", vous: "viviez", ils: "vivent" },
        imperative: { tu: "vis", nous: "vivons", vous: "vivez" } } },
    { infinitive: "mourir", translation: "to die", group: "irregular", auxiliary: "être", pastParticiple: "mort", presentParticiple: "mourant",
      conjugations: { present: { je: "meurs", tu: "meurs", il: "meurt", nous: "mourons", vous: "mourez", ils: "meurent" },
        imperfect: { je: "mourais", tu: "mourais", il: "mourait", nous: "mourions", vous: "mouriez", ils: "mouraient" },
        future: { je: "mourrai", tu: "mourras", il: "mourra", nous: "mourrons", vous: "mourrez", ils: "mourront" },
        conditional: { je: "mourrais", tu: "mourrais", il: "mourrait", nous: "mourrions", vous: "mourriez", ils: "mourraient" },
        passé_composé: { je: "suis mort(e)", tu: "es mort(e)", il: "est mort", nous: "sommes mort(e)s", vous: "êtes mort(e)(s)", ils: "sont morts" },
        subjonctif_present: { je: "meure", tu: "meures", il: "meure", nous: "mourions", vous: "mouriez", ils: "meurent" },
        imperative: { tu: "meurs", nous: "mourons", vous: "mourez" } } },
    { infinitive: "naître", translation: "to be born", group: "irregular", auxiliary: "être", pastParticiple: "né", presentParticiple: "naissant",
      conjugations: { present: { je: "nais", tu: "nais", il: "naît", nous: "naissons", vous: "naissez", ils: "naissent" },
        imperfect: { je: "naissais", tu: "naissais", il: "naissait", nous: "naissions", vous: "naissiez", ils: "naissaient" },
        future: { je: "naîtrai", tu: "naîtras", il: "naîtra", nous: "naîtrons", vous: "naîtrez", ils: "naîtront" },
        conditional: { je: "naîtrais", tu: "naîtrais", il: "naîtrait", nous: "naîtrions", vous: "naîtriez", ils: "naîtraient" },
        passé_composé: { je: "suis né(e)", tu: "es né(e)", il: "est né", nous: "sommes né(e)s", vous: "êtes né(e)(s)", ils: "sont nés" },
        subjonctif_present: { je: "naisse", tu: "naisses", il: "naisse", nous: "naissions", vous: "naissiez", ils: "naissent" },
        imperative: { tu: "nais", nous: "naissons", vous: "naissez" } } },
    { infinitive: "courir", translation: "to run", group: "irregular", auxiliary: "avoir", pastParticiple: "couru", presentParticiple: "courant",
      conjugations: { present: { je: "cours", tu: "cours", il: "court", nous: "courons", vous: "courez", ils: "courent" },
        imperfect: { je: "courais", tu: "courais", il: "courait", nous: "courions", vous: "couriez", ils: "couraient" },
        future: { je: "courrai", tu: "courras", il: "courra", nous: "courrons", vous: "courrez", ils: "courront" },
        conditional: { je: "courrais", tu: "courrais", il: "courrait", nous: "courrions", vous: "courriez", ils: "courraient" },
        passé_composé: { je: "ai couru", tu: "as couru", il: "a couru", nous: "avons couru", vous: "avez couru", ils: "ont couru" },
        subjonctif_present: { je: "coure", tu: "coures", il: "coure", nous: "courions", vous: "couriez", ils: "courent" },
        imperative: { tu: "cours", nous: "courons", vous: "courez" } } },
    { infinitive: "tenir", translation: "to hold", group: "irregular", auxiliary: "avoir", pastParticiple: "tenu", presentParticiple: "tenant",
      conjugations: { present: { je: "tiens", tu: "tiens", il: "tient", nous: "tenons", vous: "tenez", ils: "tiennent" },
        imperfect: { je: "tenais", tu: "tenais", il: "tenait", nous: "tenions", vous: "teniez", ils: "tenaient" },
        future: { je: "tiendrai", tu: "tiendras", il: "tiendra", nous: "tiendrons", vous: "tiendrez", ils: "tiendront" },
        conditional: { je: "tiendrais", tu: "tiendrais", il: "tiendrait", nous: "tiendrions", vous: "tiendriez", ils: "tiendraient" },
        passé_composé: { je: "ai tenu", tu: "as tenu", il: "a tenu", nous: "avons tenu", vous: "avez tenu", ils: "ont tenu" },
        subjonctif_present: { je: "tienne", tu: "tiennes", il: "tienne", nous: "tenions", vous: "teniez", ils: "tiennent" },
        imperative: { tu: "tiens", nous: "tenons", vous: "tenez" } } },
    { infinitive: "ouvrir", translation: "to open", group: "irregular", auxiliary: "avoir", pastParticiple: "ouvert", presentParticiple: "ouvrant",
      conjugations: { present: { je: "ouvre", tu: "ouvres", il: "ouvre", nous: "ouvrons", vous: "ouvrez", ils: "ouvrent" },
        imperfect: { je: "ouvrais", tu: "ouvrais", il: "ouvrait", nous: "ouvrions", vous: "ouvriez", ils: "ouvraient" },
        future: { je: "ouvrirai", tu: "ouvriras", il: "ouvrira", nous: "ouvrirons", vous: "ouvrirez", ils: "ouvriront" },
        conditional: { je: "ouvrirais", tu: "ouvrirais", il: "ouvrirait", nous: "ouvririons", vous: "ouvririez", ils: "ouvriraient" },
        passé_composé: { je: "ai ouvert", tu: "as ouvert", il: "a ouvert", nous: "avons ouvert", vous: "avez ouvert", ils: "ont ouvert" },
        subjonctif_present: { je: "ouvre", tu: "ouvres", il: "ouvre", nous: "ouvrions", vous: "ouvriez", ils: "ouvrent" },
        imperative: { tu: "ouvre", nous: "ouvrons", vous: "ouvrez" } } },
    { infinitive: "recevoir", translation: "to receive", group: "irregular", auxiliary: "avoir", pastParticiple: "reçu", presentParticiple: "recevant",
      conjugations: { present: { je: "reçois", tu: "reçois", il: "reçoit", nous: "recevons", vous: "recevez", ils: "reçoivent" },
        imperfect: { je: "recevais", tu: "recevais", il: "recevait", nous: "recevions", vous: "receviez", ils: "recevaient" },
        future: { je: "recevrai", tu: "recevras", il: "recevra", nous: "recevrons", vous: "recevrez", ils: "recevront" },
        conditional: { je: "recevrais", tu: "recevrais", il: "recevrait", nous: "recevrions", vous: "recevriez", ils: "recevraient" },
        passé_composé: { je: "ai reçu", tu: "as reçu", il: "a reçu", nous: "avons reçu", vous: "avez reçu", ils: "ont reçu" },
        subjonctif_present: { je: "reçoive", tu: "reçoives", il: "reçoive", nous: "recevions", vous: "receviez", ils: "reçoivent" },
        imperative: { tu: "reçois", nous: "recevons", vous: "recevez" } } },
    // REGULAR -ER VERBS (generated)
    generateERVerb("parler", "to speak"),
    generateERVerb("manger", "to eat"),
    generateERVerb("aimer", "to love/like"),
    generateERVerb("travailler", "to work"),
    generateERVerb("habiter", "to live (reside)"),
    generateERVerb("regarder", "to watch"),
    generateERVerb("écouter", "to listen"),
    generateERVerb("donner", "to give"),
    generateERVerb("trouver", "to find"),
    generateERVerb("penser", "to think"),
    generateERVerb("demander", "to ask"),
    generateERVerb("rester", "to stay"),
    generateERVerb("passer", "to pass/spend"),
    generateERVerb("porter", "to wear/carry"),
    generateERVerb("montrer", "to show"),
    generateERVerb("commencer", "to begin"),
    generateERVerb("jouer", "to play"),
    generateERVerb("arriver", "to arrive"),
    generateERVerb("chercher", "to search"),
    generateERVerb("entrer", "to enter"),
    generateERVerb("appeler", "to call"),
    generateERVerb("tomber", "to fall"),
    generateERVerb("continuer", "to continue"),
    generateERVerb("marcher", "to walk"),
    generateERVerb("monter", "to climb"),
    generateERVerb("gagner", "to win/earn"),
    generateERVerb("fermer", "to close"),
    generateERVerb("quitter", "to leave"),
    generateERVerb("acheter", "to buy"),
    generateERVerb("chanter", "to sing"),
    generateERVerb("danser", "to dance"),
    generateERVerb("nager", "to swim"),
    generateERVerb("voyager", "to travel"),
    generateERVerb("étudier", "to study"),
    generateERVerb("dessiner", "to draw"),
    generateERVerb("cuisiner", "to cook"),
    generateERVerb("expliquer", "to explain"),
    generateERVerb("utiliser", "to use"),
    generateERVerb("préparer", "to prepare"),
    generateERVerb("présenter", "to present"),
    generateERVerb("accepter", "to accept"),
    generateERVerb("refuser", "to refuse"),
    generateERVerb("oublier", "to forget"),
    generateERVerb("raconter", "to tell (story)"),
    generateERVerb("essayer", "to try"),
    generateERVerb("payer", "to pay"),
    generateERVerb("envoyer", "to send"),
    generateERVerb("créer", "to create"),
    generateERVerb("changer", "to change"),
    generateERVerb("laisser", "to leave/let"),
    generateERVerb("aider", "to help"),
    generateERVerb("décider", "to decide"),
    generateERVerb("exister", "to exist"),
    generateERVerb("imaginer", "to imagine"),
    generateERVerb("espérer", "to hope"),
    generateERVerb("détester", "to hate"),
    generateERVerb("adorer", "to adore"),
    generateERVerb("préférer", "to prefer"),
    generateERVerb("sembler", "to seem"),
    generateERVerb("toucher", "to touch"),
    generateERVerb("lever", "to raise"),
    generateERVerb("rencontrer", "to meet"),
    generateERVerb("retourner", "to return"),
    generateERVerb("inviter", "to invite"),
    generateERVerb("pleurer", "to cry"),
    generateERVerb("rêver", "to dream"),
    generateERVerb("embrasser", "to kiss/hug"),
    generateERVerb("terminer", "to finish"),
    generateERVerb("améliorer", "to improve"),
    generateERVerb("organiser", "to organize"),
    generateERVerb("participer", "to participate"),
    generateERVerb("traverser", "to cross"),
    generateERVerb("casser", "to break"),
    generateERVerb("voler", "to fly/steal"),
    generateERVerb("couper", "to cut"),
    generateERVerb("pousser", "to push"),
    generateERVerb("tirer", "to pull"),
    generateERVerb("jeter", "to throw"),
    generateERVerb("cacher", "to hide"),
    generateERVerb("garder", "to keep"),
    generateERVerb("sauver", "to save"),
    generateERVerb("exprimer", "to express"),
    generateERVerb("remarquer", "to notice"),
    generateERVerb("représenter", "to represent"),
    generateERVerb("respecter", "to respect"),
    generateERVerb("conseiller", "to advise"),
    generateERVerb("manquer", "to miss"),
    generateERVerb("occuper", "to occupy"),
    generateERVerb("proposer", "to propose"),
    generateERVerb("remercier", "to thank"),
    generateERVerb("souhaiter", "to wish"),
    generateERVerb("compter", "to count"),
    // REGULAR -IR VERBS (generated)
    generateIRVerb("finir", "to finish"),
    generateIRVerb("choisir", "to choose"),
    generateIRVerb("réussir", "to succeed"),
    generateIRVerb("remplir", "to fill"),
    generateIRVerb("grandir", "to grow up"),
    generateIRVerb("grossir", "to gain weight"),
    generateIRVerb("maigrir", "to lose weight"),
    generateIRVerb("rougir", "to blush"),
    generateIRVerb("vieillir", "to age"),
    generateIRVerb("réfléchir", "to reflect"),
    generateIRVerb("applaudir", "to applaud"),
    generateIRVerb("punir", "to punish"),
    generateIRVerb("guérir", "to heal"),
    generateIRVerb("obéir", "to obey"),
    generateIRVerb("ralentir", "to slow down"),
    generateIRVerb("atterrir", "to land"),
    generateIRVerb("bâtir", "to build"),
    generateIRVerb("définir", "to define"),
    generateIRVerb("établir", "to establish"),
    generateIRVerb("garantir", "to guarantee"),
    generateIRVerb("nourrir", "to feed"),
    generateIRVerb("avertir", "to warn"),
    generateIRVerb("accomplir", "to accomplish"),
    generateIRVerb("agir", "to act"),
    generateIRVerb("réagir", "to react"),
    generateIRVerb("saisir", "to seize"),
    generateIRVerb("fournir", "to provide"),
    // REGULAR -RE VERBS (generated)
    generateREVerb("vendre", "to sell"),
    generateREVerb("perdre", "to lose"),
    generateREVerb("rendre", "to return/give back"),
    generateREVerb("attendre", "to wait"),
    generateREVerb("entendre", "to hear"),
    generateREVerb("répondre", "to answer"),
    generateREVerb("descendre", "to go down"),
    generateREVerb("défendre", "to defend"),
    generateREVerb("dépendre", "to depend"),
    generateREVerb("confondre", "to confuse"),
    generateREVerb("fondre", "to melt"),
    generateREVerb("mordre", "to bite"),
    generateREVerb("tordre", "to twist"),
    generateREVerb("rompre", "to break"),
    generateREVerb("interrompre", "to interrupt")
];

const TENSE_NAMES = {
    present: "Présent",
    imperfect: "Imparfait", 
    future: "Futur Simple",
    conditional: "Conditionnel",
    passé_composé: "Passé Composé",
    subjonctif_present: "Subjonctif Présent",
    imperative: "Impératif"
};

const PRONOUNS = { je: "je/j'", tu: "tu", il: "il/elle/on", nous: "nous", vous: "vous", ils: "ils/elles" };
