// FRENCH MASTERY - COMPREHENSIVE VOCABULARY DATABASE
// 800+ words across 25+ categories

const FRENCH_VOCABULARY = {
    greetings: {
        name: "Greetings & Basics",
        icon: "👋",
        words: [
            { french: "bonjour", english: "hello/good morning", phonetic: "bohn-zhoor" },
            { french: "bonsoir", english: "good evening", phonetic: "bohn-swahr" },
            { french: "bonne nuit", english: "good night", phonetic: "bohn nwee" },
            { french: "salut", english: "hi/bye (informal)", phonetic: "sah-loo" },
            { french: "coucou", english: "hey (very informal)", phonetic: "koo-koo" },
            { french: "au revoir", english: "goodbye", phonetic: "oh ruh-vwahr" },
            { french: "à bientôt", english: "see you soon", phonetic: "ah byehn-toh" },
            { french: "à demain", english: "see you tomorrow", phonetic: "ah duh-mahn" },
            { french: "à plus tard", english: "see you later", phonetic: "ah ploo tahr" },
            { french: "à tout à l'heure", english: "see you in a bit", phonetic: "ah too tah luhr" },
            { french: "merci", english: "thank you", phonetic: "mehr-see" },
            { french: "merci beaucoup", english: "thank you very much", phonetic: "mehr-see boh-koo" },
            { french: "merci bien", english: "thanks a lot", phonetic: "mehr-see byehn" },
            { french: "de rien", english: "you're welcome", phonetic: "duh ryehn" },
            { french: "je vous en prie", english: "you're welcome (formal)", phonetic: "zhuh voo zahn pree" },
            { french: "il n'y a pas de quoi", english: "don't mention it", phonetic: "eel nyah pah duh kwah" },
            { french: "s'il vous plaît", english: "please (formal)", phonetic: "seel voo pleh" },
            { french: "s'il te plaît", english: "please (informal)", phonetic: "seel tuh pleh" },
            { french: "excusez-moi", english: "excuse me (formal)", phonetic: "eks-koo-zay mwah" },
            { french: "excuse-moi", english: "excuse me (informal)", phonetic: "eks-kooz mwah" },
            { french: "pardon", english: "sorry/pardon", phonetic: "pahr-dohn" },
            { french: "désolé(e)", english: "sorry", phonetic: "day-zoh-lay" },
            { french: "comment allez-vous?", english: "how are you? (formal)", phonetic: "koh-mahn tah-lay voo" },
            { french: "comment vas-tu?", english: "how are you? (informal)", phonetic: "koh-mahn vah too" },
            { french: "ça va?", english: "how's it going?", phonetic: "sah vah" },
            { french: "ça va bien", english: "I'm fine", phonetic: "sah vah byehn" },
            { french: "très bien", english: "very well", phonetic: "treh byehn" },
            { french: "pas mal", english: "not bad", phonetic: "pah mahl" },
            { french: "comme ci comme ça", english: "so-so", phonetic: "kohm see kohm sah" },
            { french: "oui", english: "yes", phonetic: "wee" },
            { french: "non", english: "no", phonetic: "nohn" },
            { french: "peut-être", english: "maybe", phonetic: "puh-tehtr" },
            { french: "bien sûr", english: "of course", phonetic: "byehn soor" },
            { french: "d'accord", english: "okay/agreed", phonetic: "dah-kohr" },
            { french: "enchanté(e)", english: "nice to meet you", phonetic: "ahn-shahn-tay" },
            { french: "ravi(e) de vous connaître", english: "pleased to meet you", phonetic: "rah-vee duh voo koh-nehtr" },
            { french: "je m'appelle", english: "my name is", phonetic: "zhuh mah-pell" },
            { french: "comment vous appelez-vous?", english: "what's your name? (formal)", phonetic: "koh-mahn voo zah-play voo" },
            { french: "bienvenue", english: "welcome", phonetic: "byehn-vuh-noo" },
            { french: "félicitations", english: "congratulations", phonetic: "fay-lee-see-tah-syohn" },
            { french: "bon anniversaire", english: "happy birthday", phonetic: "bohn ah-nee-vehr-sehr" },
            { french: "bonne année", english: "happy new year", phonetic: "bohn ah-nay" },
            { french: "joyeux Noël", english: "merry Christmas", phonetic: "zhwah-yuh noh-ehl" },
            { french: "bonne chance", english: "good luck", phonetic: "bohn shahns" },
            { french: "bon courage", english: "hang in there", phonetic: "bohn koo-rahzh" },
            { french: "bon appétit", english: "enjoy your meal", phonetic: "bohn ah-pay-tee" },
            { french: "santé!", english: "cheers!", phonetic: "sahn-tay" },
            { french: "à vos souhaits", english: "bless you (after sneeze)", phonetic: "ah voh sweh" }
        ]
    },
    numbers: {
        name: "Numbers",
        icon: "🔢",
        words: [
            { french: "zéro", english: "zero", phonetic: "zay-roh" },
            { french: "un", english: "one", phonetic: "uhn" },
            { french: "deux", english: "two", phonetic: "duh" },
            { french: "trois", english: "three", phonetic: "twah" },
            { french: "quatre", english: "four", phonetic: "katr" },
            { french: "cinq", english: "five", phonetic: "sank" },
            { french: "six", english: "six", phonetic: "sees" },
            { french: "sept", english: "seven", phonetic: "seht" },
            { french: "huit", english: "eight", phonetic: "weet" },
            { french: "neuf", english: "nine", phonetic: "nuhf" },
            { french: "dix", english: "ten", phonetic: "dees" },
            { french: "onze", english: "eleven", phonetic: "ohnz" },
            { french: "douze", english: "twelve", phonetic: "dooz" },
            { french: "treize", english: "thirteen", phonetic: "trehz" },
            { french: "quatorze", english: "fourteen", phonetic: "kah-torz" },
            { french: "quinze", english: "fifteen", phonetic: "kahnz" },
            { french: "seize", english: "sixteen", phonetic: "sehz" },
            { french: "dix-sept", english: "seventeen", phonetic: "dee-seht" },
            { french: "dix-huit", english: "eighteen", phonetic: "deez-weet" },
            { french: "dix-neuf", english: "nineteen", phonetic: "deez-nuhf" },
            { french: "vingt", english: "twenty", phonetic: "vahn" },
            { french: "vingt et un", english: "twenty-one", phonetic: "vahn-tay-uhn" },
            { french: "vingt-deux", english: "twenty-two", phonetic: "vahn-duh" },
            { french: "trente", english: "thirty", phonetic: "trahnt" },
            { french: "quarante", english: "forty", phonetic: "kah-rahnt" },
            { french: "cinquante", english: "fifty", phonetic: "sahn-kahnt" },
            { french: "soixante", english: "sixty", phonetic: "swah-sahnt" },
            { french: "soixante-dix", english: "seventy", phonetic: "swah-sahnt-dees" },
            { french: "quatre-vingts", english: "eighty", phonetic: "katr-vahn" },
            { french: "quatre-vingt-dix", english: "ninety", phonetic: "katr-vahn-dees" },
            { french: "cent", english: "one hundred", phonetic: "sahn" },
            { french: "deux cents", english: "two hundred", phonetic: "duh sahn" },
            { french: "mille", english: "one thousand", phonetic: "meel" },
            { french: "un million", english: "one million", phonetic: "uhn mee-lyohn" },
            { french: "un milliard", english: "one billion", phonetic: "uhn mee-lyahr" },
            { french: "premier/première", english: "first", phonetic: "pruh-myay/pruh-myehr" },
            { french: "deuxième", english: "second", phonetic: "duh-zyehm" },
            { french: "troisième", english: "third", phonetic: "twah-zyehm" },
            { french: "quatrième", english: "fourth", phonetic: "kah-tree-ehm" },
            { french: "cinquième", english: "fifth", phonetic: "sahn-kyehm" },
            { french: "sixième", english: "sixth", phonetic: "see-zyehm" },
            { french: "septième", english: "seventh", phonetic: "seh-tyehm" },
            { french: "huitième", english: "eighth", phonetic: "wee-tyehm" },
            { french: "neuvième", english: "ninth", phonetic: "nuh-vyehm" },
            { french: "dixième", english: "tenth", phonetic: "dee-zyehm" },
            { french: "dernier/dernière", english: "last", phonetic: "dehr-nyay/dehr-nyehr" },
            { french: "la moitié", english: "half", phonetic: "lah mwah-tyay" },
            { french: "un quart", english: "a quarter", phonetic: "uhn kahr" },
            { french: "un tiers", english: "a third", phonetic: "uhn tyehr" },
            { french: "le double", english: "double", phonetic: "luh doobl" },
            { french: "le triple", english: "triple", phonetic: "luh treephl" }
        ]
    },
    colors: {
        name: "Colors",
        icon: "🎨",
        words: [
            { french: "rouge", english: "red", phonetic: "roozh" },
            { french: "bleu", english: "blue", phonetic: "bluh" },
            { french: "bleu clair", english: "light blue", phonetic: "bluh klehr" },
            { french: "bleu foncé", english: "dark blue", phonetic: "bluh fohn-say" },
            { french: "bleu marine", english: "navy blue", phonetic: "bluh mah-reen" },
            { french: "vert", english: "green", phonetic: "vehr" },
            { french: "vert clair", english: "light green", phonetic: "vehr klehr" },
            { french: "vert foncé", english: "dark green", phonetic: "vehr fohn-say" },
            { french: "jaune", english: "yellow", phonetic: "zhohn" },
            { french: "orange", english: "orange", phonetic: "oh-rahnzh" },
            { french: "violet", english: "purple", phonetic: "vyoh-leh" },
            { french: "rose", english: "pink", phonetic: "rohz" },
            { french: "noir", english: "black", phonetic: "nwahr" },
            { french: "blanc", english: "white", phonetic: "blahn" },
            { french: "gris", english: "gray", phonetic: "gree" },
            { french: "marron", english: "brown", phonetic: "mah-rohn" },
            { french: "brun", english: "brown (hair)", phonetic: "bruhn" },
            { french: "beige", english: "beige", phonetic: "behzh" },
            { french: "crème", english: "cream", phonetic: "krehm" },
            { french: "doré", english: "golden", phonetic: "doh-ray" },
            { french: "argenté", english: "silver", phonetic: "ahr-zhahn-tay" },
            { french: "bronze", english: "bronze", phonetic: "brohnz" },
            { french: "bordeaux", english: "burgundy", phonetic: "bohr-doh" },
            { french: "turquoise", english: "turquoise", phonetic: "toor-kwahz" },
            { french: "corail", english: "coral", phonetic: "koh-rahy" },
            { french: "clair", english: "light", phonetic: "klehr" },
            { french: "foncé", english: "dark", phonetic: "fohn-say" },
            { french: "vif", english: "bright/vivid", phonetic: "veef" },
            { french: "pâle", english: "pale", phonetic: "pahl" },
            { french: "multicolore", english: "multicolored", phonetic: "mool-tee-koh-lohr" }
        ]
    },
    family: {
        name: "Family & Relationships",
        icon: "👨‍👩‍👧‍👦",
        words: [
            { french: "la famille", english: "family", phonetic: "lah fah-mee" },
            { french: "le père", english: "father", phonetic: "luh pehr" },
            { french: "la mère", english: "mother", phonetic: "lah mehr" },
            { french: "papa", english: "dad", phonetic: "pah-pah" },
            { french: "maman", english: "mom", phonetic: "mah-mahn" },
            { french: "les parents", english: "parents", phonetic: "lay pah-rahn" },
            { french: "le fils", english: "son", phonetic: "luh fees" },
            { french: "la fille", english: "daughter", phonetic: "lah fee" },
            { french: "l'enfant", english: "child", phonetic: "lahn-fahn" },
            { french: "les enfants", english: "children", phonetic: "lay zahn-fahn" },
            { french: "le frère", english: "brother", phonetic: "luh frehr" },
            { french: "la sœur", english: "sister", phonetic: "lah suhr" },
            { french: "le frère jumeau", english: "twin brother", phonetic: "luh frehr zhoo-moh" },
            { french: "le demi-frère", english: "half-brother", phonetic: "luh duh-mee frehr" },
            { french: "la demi-sœur", english: "half-sister", phonetic: "lah duh-mee suhr" },
            { french: "le grand-père", english: "grandfather", phonetic: "luh grahn-pehr" },
            { french: "la grand-mère", english: "grandmother", phonetic: "lah grahn-mehr" },
            { french: "les grands-parents", english: "grandparents", phonetic: "lay grahn-pah-rahn" },
            { french: "le petit-fils", english: "grandson", phonetic: "luh puh-tee fees" },
            { french: "la petite-fille", english: "granddaughter", phonetic: "lah puh-teet fee" },
            { french: "l'oncle", english: "uncle", phonetic: "lohnkl" },
            { french: "la tante", english: "aunt", phonetic: "lah tahnt" },
            { french: "le cousin", english: "cousin (m)", phonetic: "luh koo-zahn" },
            { french: "la cousine", english: "cousin (f)", phonetic: "lah koo-zeen" },
            { french: "le neveu", english: "nephew", phonetic: "luh nuh-vuh" },
            { french: "la nièce", english: "niece", phonetic: "lah nyehs" },
            { french: "le mari", english: "husband", phonetic: "luh mah-ree" },
            { french: "la femme", english: "wife", phonetic: "lah fahm" },
            { french: "l'époux", english: "spouse (m)", phonetic: "lay-poo" },
            { french: "l'épouse", english: "spouse (f)", phonetic: "lay-pooz" },
            { french: "le fiancé", english: "fiancé", phonetic: "luh fyahn-say" },
            { french: "la fiancée", english: "fiancée", phonetic: "lah fyahn-say" },
            { french: "le copain", english: "boyfriend", phonetic: "luh koh-pahn" },
            { french: "la copine", english: "girlfriend", phonetic: "lah koh-peen" },
            { french: "le petit ami", english: "boyfriend", phonetic: "luh puh-tee tah-mee" },
            { french: "la petite amie", english: "girlfriend", phonetic: "lah puh-teet ah-mee" },
            { french: "le beau-père", english: "father-in-law/stepfather", phonetic: "luh boh-pehr" },
            { french: "la belle-mère", english: "mother-in-law/stepmother", phonetic: "lah behl-mehr" },
            { french: "le beau-frère", english: "brother-in-law", phonetic: "luh boh-frehr" },
            { french: "la belle-sœur", english: "sister-in-law", phonetic: "lah behl-suhr" },
            { french: "le gendre", english: "son-in-law", phonetic: "luh zhahndr" },
            { french: "la belle-fille", english: "daughter-in-law", phonetic: "lah behl-fee" },
            { french: "le beau-fils", english: "stepson", phonetic: "luh boh-fees" },
            { french: "le parrain", english: "godfather", phonetic: "luh pah-rahn" },
            { french: "la marraine", english: "godmother", phonetic: "lah mah-rehn" },
            { french: "le filleul", english: "godson", phonetic: "luh fee-yuhl" },
            { french: "la filleule", english: "goddaughter", phonetic: "lah fee-yuhl" },
            { french: "l'ami(e)", english: "friend", phonetic: "lah-mee" },
            { french: "le/la voisin(e)", english: "neighbor", phonetic: "luh/lah vwah-zahn" },
            { french: "le/la collègue", english: "colleague", phonetic: "luh/lah koh-lehg" }
        ]
    },
    food: {
        name: "Food & Drinks",
        icon: "🍽️",
        words: [
            { french: "le pain", english: "bread", phonetic: "luh pahn" },
            { french: "la baguette", english: "baguette", phonetic: "lah bah-geht" },
            { french: "le croissant", english: "croissant", phonetic: "luh kwah-sahn" },
            { french: "le fromage", english: "cheese", phonetic: "luh froh-mahzh" },
            { french: "le beurre", english: "butter", phonetic: "luh buhr" },
            { french: "la confiture", english: "jam", phonetic: "lah kohn-fee-toor" },
            { french: "le miel", english: "honey", phonetic: "luh myehl" },
            { french: "l'œuf", english: "egg", phonetic: "luhf" },
            { french: "les œufs", english: "eggs", phonetic: "lay zuhf" },
            { french: "le lait", english: "milk", phonetic: "luh leh" },
            { french: "la crème", english: "cream", phonetic: "lah krehm" },
            { french: "le yaourt", english: "yogurt", phonetic: "luh yah-oort" },
            { french: "le vin", english: "wine", phonetic: "luh vahn" },
            { french: "le vin rouge", english: "red wine", phonetic: "luh vahn roozh" },
            { french: "le vin blanc", english: "white wine", phonetic: "luh vahn blahn" },
            { french: "l'eau", english: "water", phonetic: "loh" },
            { french: "l'eau gazeuse", english: "sparkling water", phonetic: "loh gah-zuhz" },
            { french: "l'eau plate", english: "still water", phonetic: "loh plaht" },
            { french: "le café", english: "coffee", phonetic: "luh kah-fay" },
            { french: "le café crème", english: "coffee with cream", phonetic: "luh kah-fay krehm" },
            { french: "le café au lait", english: "coffee with milk", phonetic: "luh kah-fay oh leh" },
            { french: "l'expresso", english: "espresso", phonetic: "lehks-preh-soh" },
            { french: "le thé", english: "tea", phonetic: "luh tay" },
            { french: "le thé vert", english: "green tea", phonetic: "luh tay vehr" },
            { french: "le chocolat chaud", english: "hot chocolate", phonetic: "luh shoh-koh-lah shoh" },
            { french: "le jus", english: "juice", phonetic: "luh zhoo" },
            { french: "le jus d'orange", english: "orange juice", phonetic: "luh zhoo doh-rahnzh" },
            { french: "la bière", english: "beer", phonetic: "lah byehr" },
            { french: "le cidre", english: "cider", phonetic: "luh seedr" },
            { french: "la viande", english: "meat", phonetic: "lah vyahnd" },
            { french: "le bœuf", english: "beef", phonetic: "luh buhf" },
            { french: "le steak", english: "steak", phonetic: "luh stehk" },
            { french: "le porc", english: "pork", phonetic: "luh pohr" },
            { french: "le jambon", english: "ham", phonetic: "luh zhahm-bohn" },
            { french: "le poulet", english: "chicken", phonetic: "luh poo-leh" },
            { french: "la dinde", english: "turkey", phonetic: "lah dahnd" },
            { french: "le canard", english: "duck", phonetic: "luh kah-nahr" },
            { french: "l'agneau", english: "lamb", phonetic: "lah-nyoh" },
            { french: "le veau", english: "veal", phonetic: "luh voh" },
            { french: "la saucisse", english: "sausage", phonetic: "lah soh-sees" },
            { french: "le bacon", english: "bacon", phonetic: "luh bay-kohn" },
            { french: "le poisson", english: "fish", phonetic: "luh pwah-sohn" },
            { french: "le saumon", english: "salmon", phonetic: "luh soh-mohn" },
            { french: "le thon", english: "tuna", phonetic: "luh tohn" },
            { french: "la truite", english: "trout", phonetic: "lah trweet" },
            { french: "la morue", english: "cod", phonetic: "lah moh-roo" },
            { french: "les crevettes", english: "shrimp", phonetic: "lay kruh-veht" },
            { french: "les moules", english: "mussels", phonetic: "lay mool" },
            { french: "les huîtres", english: "oysters", phonetic: "lay weetr" },
            { french: "le homard", english: "lobster", phonetic: "luh oh-mahr" },
            { french: "le crabe", english: "crab", phonetic: "luh krahb" },
            { french: "les fruits de mer", english: "seafood", phonetic: "lay frwee duh mehr" },
            { french: "les légumes", english: "vegetables", phonetic: "lay lay-goom" },
            { french: "la salade", english: "salad/lettuce", phonetic: "lah sah-lahd" },
            { french: "la tomate", english: "tomato", phonetic: "lah toh-maht" },
            { french: "la carotte", english: "carrot", phonetic: "lah kah-roht" },
            { french: "la pomme de terre", english: "potato", phonetic: "lah pohm duh tehr" },
            { french: "les frites", english: "fries", phonetic: "lay freet" },
            { french: "l'oignon", english: "onion", phonetic: "loh-nyohn" },
            { french: "l'ail", english: "garlic", phonetic: "lahy" },
            { french: "le poivron", english: "bell pepper", phonetic: "luh pwah-vrohn" },
            { french: "le concombre", english: "cucumber", phonetic: "luh kohn-kohmr" },
            { french: "les haricots verts", english: "green beans", phonetic: "lay ah-ree-koh vehr" },
            { french: "les petits pois", english: "peas", phonetic: "lay puh-tee pwah" },
            { french: "le maïs", english: "corn", phonetic: "luh mah-ees" },
            { french: "les épinards", english: "spinach", phonetic: "lay zay-pee-nahr" },
            { french: "le brocoli", english: "broccoli", phonetic: "luh broh-koh-lee" },
            { french: "le chou", english: "cabbage", phonetic: "luh shoo" },
            { french: "le chou-fleur", english: "cauliflower", phonetic: "luh shoo-fluhr" },
            { french: "l'aubergine", english: "eggplant", phonetic: "loh-behr-zheen" },
            { french: "la courgette", english: "zucchini", phonetic: "lah koor-zheht" },
            { french: "le champignon", english: "mushroom", phonetic: "luh shahm-pee-nyohn" },
            { french: "les fruits", english: "fruits", phonetic: "lay frwee" },
            { french: "la pomme", english: "apple", phonetic: "lah pohm" },
            { french: "la poire", english: "pear", phonetic: "lah pwahr" },
            { french: "l'orange", english: "orange", phonetic: "loh-rahnzh" },
            { french: "le citron", english: "lemon", phonetic: "luh see-trohn" },
            { french: "le citron vert", english: "lime", phonetic: "luh see-trohn vehr" },
            { french: "la banane", english: "banana", phonetic: "lah bah-nahn" },
            { french: "la fraise", english: "strawberry", phonetic: "lah frehz" },
            { french: "la framboise", english: "raspberry", phonetic: "lah frahm-bwahz" },
            { french: "la myrtille", english: "blueberry", phonetic: "lah meer-tee" },
            { french: "la cerise", english: "cherry", phonetic: "lah suh-reez" },
            { french: "le raisin", english: "grape", phonetic: "luh reh-zahn" },
            { french: "la pêche", english: "peach", phonetic: "lah pehsh" },
            { french: "l'abricot", english: "apricot", phonetic: "lah-bree-koh" },
            { french: "la prune", english: "plum", phonetic: "lah proon" },
            { french: "le melon", english: "melon", phonetic: "luh muh-lohn" },
            { french: "la pastèque", english: "watermelon", phonetic: "lah pahs-tehk" },
            { french: "l'ananas", english: "pineapple", phonetic: "lah-nah-nahs" },
            { french: "la mangue", english: "mango", phonetic: "lah mahng" },
            { french: "la noix de coco", english: "coconut", phonetic: "lah nwah duh koh-koh" },
            { french: "le riz", english: "rice", phonetic: "luh ree" },
            { french: "les pâtes", english: "pasta", phonetic: "lay paht" },
            { french: "les nouilles", english: "noodles", phonetic: "lay noo-ee" },
            { french: "la soupe", english: "soup", phonetic: "lah soop" },
            { french: "le potage", english: "thick soup", phonetic: "luh poh-tahzh" },
            { french: "la sauce", english: "sauce", phonetic: "lah sohs" },
            { french: "le dessert", english: "dessert", phonetic: "luh deh-sehr" },
            { french: "le gâteau", english: "cake", phonetic: "luh gah-toh" },
            { french: "la tarte", english: "pie/tart", phonetic: "lah tahrt" },
            { french: "la glace", english: "ice cream", phonetic: "lah glahs" },
            { french: "le chocolat", english: "chocolate", phonetic: "luh shoh-koh-lah" },
            { french: "les bonbons", english: "candy", phonetic: "lay bohn-bohn" },
            { french: "le biscuit", english: "cookie/biscuit", phonetic: "luh bees-kwee" },
            { french: "la crêpe", english: "crepe", phonetic: "lah krehp" },
            { french: "le sucre", english: "sugar", phonetic: "luh sookr" },
            { french: "le sel", english: "salt", phonetic: "luh sehl" },
            { french: "le poivre", english: "pepper", phonetic: "luh pwahvr" },
            { french: "l'huile", english: "oil", phonetic: "lweel" },
            { french: "le vinaigre", english: "vinegar", phonetic: "luh vee-nehgr" },
            { french: "la moutarde", english: "mustard", phonetic: "lah moo-tahrd" },
            { french: "la mayonnaise", english: "mayonnaise", phonetic: "lah mah-yoh-nehz" },
            { french: "le ketchup", english: "ketchup", phonetic: "luh keht-chuhp" }
        ]
    },
    meals: {
        name: "Meals & Dining",
        icon: "🍴",
        words: [
            { french: "le repas", english: "meal", phonetic: "luh ruh-pah" },
            { french: "le petit-déjeuner", english: "breakfast", phonetic: "luh puh-tee day-zhuh-nay" },
            { french: "le déjeuner", english: "lunch", phonetic: "luh day-zhuh-nay" },
            { french: "le dîner", english: "dinner", phonetic: "luh dee-nay" },
            { french: "le goûter", english: "snack (afternoon)", phonetic: "luh goo-tay" },
            { french: "l'entrée", english: "starter/appetizer", phonetic: "lahn-tray" },
            { french: "le plat principal", english: "main course", phonetic: "luh plah prahn-see-pahl" },
            { french: "le plat du jour", english: "dish of the day", phonetic: "luh plah doo zhoor" },
            { french: "l'addition", english: "the bill", phonetic: "lah-dee-syohn" },
            { french: "le menu", english: "menu", phonetic: "luh muh-noo" },
            { french: "la carte", english: "menu (à la carte)", phonetic: "lah kahrt" },
            { french: "la réservation", english: "reservation", phonetic: "lah ray-zehr-vah-syohn" },
            { french: "le serveur", english: "waiter", phonetic: "luh sehr-vuhr" },
            { french: "la serveuse", english: "waitress", phonetic: "lah sehr-vuhz" },
            { french: "le pourboire", english: "tip", phonetic: "luh poor-bwahr" },
            { french: "l'assiette", english: "plate", phonetic: "lah-syeht" },
            { french: "le bol", english: "bowl", phonetic: "luh bohl" },
            { french: "le verre", english: "glass", phonetic: "luh vehr" },
            { french: "la tasse", english: "cup", phonetic: "lah tahs" },
            { french: "la fourchette", english: "fork", phonetic: "lah foor-sheht" },
            { french: "le couteau", english: "knife", phonetic: "luh koo-toh" },
            { french: "la cuillère", english: "spoon", phonetic: "lah kwee-yehr" },
            { french: "la serviette", english: "napkin", phonetic: "lah sehr-vyeht" },
            { french: "la bouteille", english: "bottle", phonetic: "lah boo-tay" },
            { french: "la carafe", english: "carafe/pitcher", phonetic: "lah kah-rahf" },
            { french: "commander", english: "to order", phonetic: "koh-mahn-day" },
            { french: "goûter", english: "to taste", phonetic: "goo-tay" },
            { french: "délicieux", english: "delicious", phonetic: "day-lee-syuh" },
            { french: "savoureux", english: "tasty", phonetic: "sah-voo-ruh" },
            { french: "épicé", english: "spicy", phonetic: "ay-pee-say" },
            { french: "sucré", english: "sweet", phonetic: "soo-kray" },
            { french: "salé", english: "salty", phonetic: "sah-lay" },
            { french: "amer", english: "bitter", phonetic: "ah-mehr" },
            { french: "aigre", english: "sour", phonetic: "ehgr" },
            { french: "fade", english: "bland", phonetic: "fahd" },
            { french: "cru", english: "raw", phonetic: "kroo" },
            { french: "cuit", english: "cooked", phonetic: "kwee" },
            { french: "grillé", english: "grilled", phonetic: "gree-yay" },
            { french: "rôti", english: "roasted", phonetic: "roh-tee" },
            { french: "frit", english: "fried", phonetic: "free" },
            { french: "bouilli", english: "boiled", phonetic: "boo-yee" }
        ]
    },
    time: {
        name: "Time & Calendar",
        icon: "🕐",
        words: [
            { french: "le temps", english: "time", phonetic: "luh tahn" },
            { french: "l'heure", english: "hour/time", phonetic: "luhr" },
            { french: "la minute", english: "minute", phonetic: "lah mee-noot" },
            { french: "la seconde", english: "second", phonetic: "lah suh-kohnd" },
            { french: "le jour", english: "day", phonetic: "luh zhoor" },
            { french: "la journée", english: "daytime/day", phonetic: "lah zhoor-nay" },
            { french: "la semaine", english: "week", phonetic: "lah suh-mehn" },
            { french: "le week-end", english: "weekend", phonetic: "luh wee-kehnd" },
            { french: "le mois", english: "month", phonetic: "luh mwah" },
            { french: "l'année", english: "year", phonetic: "lah-nay" },
            { french: "le siècle", english: "century", phonetic: "luh syehkl" },
            { french: "aujourd'hui", english: "today", phonetic: "oh-zhoor-dwee" },
            { french: "demain", english: "tomorrow", phonetic: "duh-mahn" },
            { french: "après-demain", english: "day after tomorrow", phonetic: "ah-preh duh-mahn" },
            { french: "hier", english: "yesterday", phonetic: "yehr" },
            { french: "avant-hier", english: "day before yesterday", phonetic: "ah-vahn yehr" },
            { french: "maintenant", english: "now", phonetic: "mahn-tuh-nahn" },
            { french: "bientôt", english: "soon", phonetic: "byahn-toh" },
            { french: "tout de suite", english: "right away", phonetic: "too duh sweet" },
            { french: "plus tard", english: "later", phonetic: "ploo tahr" },
            { french: "tôt", english: "early", phonetic: "toh" },
            { french: "tard", english: "late", phonetic: "tahr" },
            { french: "le matin", english: "morning", phonetic: "luh mah-tahn" },
            { french: "l'après-midi", english: "afternoon", phonetic: "lah-preh mee-dee" },
            { french: "le soir", english: "evening", phonetic: "luh swahr" },
            { french: "la nuit", english: "night", phonetic: "lah nwee" },
            { french: "minuit", english: "midnight", phonetic: "mee-nwee" },
            { french: "midi", english: "noon", phonetic: "mee-dee" },
            { french: "lundi", english: "Monday", phonetic: "luhn-dee" },
            { french: "mardi", english: "Tuesday", phonetic: "mahr-dee" },
            { french: "mercredi", english: "Wednesday", phonetic: "mehr-kruh-dee" },
            { french: "jeudi", english: "Thursday", phonetic: "zhuh-dee" },
            { french: "vendredi", english: "Friday", phonetic: "vahn-druh-dee" },
            { french: "samedi", english: "Saturday", phonetic: "sahm-dee" },
            { french: "dimanche", english: "Sunday", phonetic: "dee-mahnsh" },
            { french: "janvier", english: "January", phonetic: "zhahn-vyay" },
            { french: "février", english: "February", phonetic: "fay-vryay" },
            { french: "mars", english: "March", phonetic: "mahrs" },
            { french: "avril", english: "April", phonetic: "ah-vreel" },
            { french: "mai", english: "May", phonetic: "meh" },
            { french: "juin", english: "June", phonetic: "zhwahn" },
            { french: "juillet", english: "July", phonetic: "zhwee-yeh" },
            { french: "août", english: "August", phonetic: "oot" },
            { french: "septembre", english: "September", phonetic: "sehp-tahmr" },
            { french: "octobre", english: "October", phonetic: "ohk-tohbr" },
            { french: "novembre", english: "November", phonetic: "noh-vahmr" },
            { french: "décembre", english: "December", phonetic: "day-sahmr" },
            { french: "le printemps", english: "spring", phonetic: "luh prahn-tahn" },
            { french: "l'été", english: "summer", phonetic: "lay-tay" },
            { french: "l'automne", english: "autumn/fall", phonetic: "loh-tohn" },
            { french: "l'hiver", english: "winter", phonetic: "lee-vehr" },
            { french: "le calendrier", english: "calendar", phonetic: "luh kah-lahn-dryay" },
            { french: "la date", english: "date", phonetic: "lah daht" },
            { french: "l'anniversaire", english: "birthday/anniversary", phonetic: "lah-nee-vehr-sehr" },
            { french: "le jour férié", english: "public holiday", phonetic: "luh zhoor fay-ryay" },
            { french: "les vacances", english: "vacation/holidays", phonetic: "lay vah-kahns" }
        ]
    },
    places: {
        name: "Places & Buildings",
        icon: "🏠",
        words: [
            { french: "la maison", english: "house/home", phonetic: "lah meh-zohn" },
            { french: "l'appartement", english: "apartment", phonetic: "lah-pahr-tuh-mahn" },
            { french: "l'immeuble", english: "building", phonetic: "lee-muhbl" },
            { french: "la rue", english: "street", phonetic: "lah roo" },
            { french: "l'avenue", english: "avenue", phonetic: "lah-vuh-noo" },
            { french: "le boulevard", english: "boulevard", phonetic: "luh bool-vahr" },
            { french: "la place", english: "square/plaza", phonetic: "lah plahs" },
            { french: "le quartier", english: "neighborhood", phonetic: "luh kahr-tyay" },
            { french: "la ville", english: "city/town", phonetic: "lah veel" },
            { french: "le village", english: "village", phonetic: "luh vee-lahzh" },
            { french: "la banlieue", english: "suburbs", phonetic: "lah bahn-lyuh" },
            { french: "la campagne", english: "countryside", phonetic: "lah kahm-pahn-yuh" },
            { french: "le pays", english: "country", phonetic: "luh pay-ee" },
            { french: "la région", english: "region", phonetic: "lah ray-zhyohn" },
            { french: "l'école", english: "school", phonetic: "lay-kohl" },
            { french: "le collège", english: "middle school", phonetic: "luh koh-lehzh" },
            { french: "le lycée", english: "high school", phonetic: "luh lee-say" },
            { french: "l'université", english: "university", phonetic: "loo-nee-vehr-see-tay" },
            { french: "la bibliothèque", english: "library", phonetic: "lah bee-blee-oh-tehk" },
            { french: "le bureau", english: "office", phonetic: "luh boo-roh" },
            { french: "l'usine", english: "factory", phonetic: "loo-zeen" },
            { french: "l'entreprise", english: "company/business", phonetic: "lahn-truh-preez" },
            { french: "l'hôpital", english: "hospital", phonetic: "loh-pee-tahl" },
            { french: "la clinique", english: "clinic", phonetic: "lah klee-neek" },
            { french: "la pharmacie", english: "pharmacy", phonetic: "lah fahr-mah-see" },
            { french: "le cabinet médical", english: "doctor's office", phonetic: "luh kah-bee-neh may-dee-kahl" },
            { french: "le magasin", english: "store/shop", phonetic: "luh mah-gah-zahn" },
            { french: "la boutique", english: "boutique/shop", phonetic: "lah boo-teek" },
            { french: "le supermarché", english: "supermarket", phonetic: "luh soo-pehr-mahr-shay" },
            { french: "l'hypermarché", english: "hypermarket", phonetic: "lee-pehr-mahr-shay" },
            { french: "le centre commercial", english: "shopping center", phonetic: "luh sahntr koh-mehr-syahl" },
            { french: "le marché", english: "market", phonetic: "luh mahr-shay" },
            { french: "la boulangerie", english: "bakery", phonetic: "lah boo-lahnzh-ree" },
            { french: "la pâtisserie", english: "pastry shop", phonetic: "lah pah-tee-suh-ree" },
            { french: "la boucherie", english: "butcher shop", phonetic: "lah boo-shuh-ree" },
            { french: "la charcuterie", english: "deli", phonetic: "lah shahr-koo-tuh-ree" },
            { french: "la poissonnerie", english: "fish market", phonetic: "lah pwah-sohn-ree" },
            { french: "l'épicerie", english: "grocery store", phonetic: "lay-pee-suh-ree" },
            { french: "la librairie", english: "bookstore", phonetic: "lah lee-breh-ree" },
            { french: "la banque", english: "bank", phonetic: "lah bahnk" },
            { french: "la poste", english: "post office", phonetic: "lah pohst" },
            { french: "le commissariat", english: "police station", phonetic: "luh koh-mee-sah-ryah" },
            { french: "la caserne de pompiers", english: "fire station", phonetic: "lah kah-zehrn duh pohm-pyay" },
            { french: "la mairie", english: "town hall", phonetic: "lah meh-ree" },
            { french: "l'hôtel de ville", english: "city hall", phonetic: "loh-tehl duh veel" },
            { french: "l'ambassade", english: "embassy", phonetic: "lahm-bah-sahd" },
            { french: "le restaurant", english: "restaurant", phonetic: "luh rehs-toh-rahn" },
            { french: "le café", english: "café", phonetic: "luh kah-fay" },
            { french: "le bar", english: "bar", phonetic: "luh bahr" },
            { french: "la discothèque", english: "nightclub", phonetic: "lah dees-koh-tehk" },
            { french: "le cinéma", english: "cinema/movie theater", phonetic: "luh see-nay-mah" },
            { french: "le théâtre", english: "theater", phonetic: "luh tay-ahtr" },
            { french: "le musée", english: "museum", phonetic: "luh moo-zay" },
            { french: "la galerie d'art", english: "art gallery", phonetic: "lah gah-luh-ree dahr" },
            { french: "l'opéra", english: "opera house", phonetic: "loh-pay-rah" },
            { french: "le stade", english: "stadium", phonetic: "luh stahd" },
            { french: "la salle de sport", english: "gym", phonetic: "lah sahl duh spohr" },
            { french: "la piscine", english: "swimming pool", phonetic: "lah pee-seen" },
            { french: "le parc", english: "park", phonetic: "luh pahrk" },
            { french: "le jardin", english: "garden", phonetic: "luh zhahr-dahn" },
            { french: "le jardin public", english: "public garden", phonetic: "luh zhahr-dahn poo-bleek" },
            { french: "la gare", english: "train station", phonetic: "lah gahr" },
            { french: "la gare routière", english: "bus station", phonetic: "lah gahr roo-tyehr" },
            { french: "l'aéroport", english: "airport", phonetic: "lah-ay-roh-pohr" },
            { french: "le port", english: "port/harbor", phonetic: "luh pohr" },
            { french: "l'hôtel", english: "hotel", phonetic: "loh-tehl" },
            { french: "l'auberge", english: "inn", phonetic: "loh-behrzh" },
            { french: "l'église", english: "church", phonetic: "lay-gleez" },
            { french: "la cathédrale", english: "cathedral", phonetic: "lah kah-tay-drahl" },
            { french: "la mosquée", english: "mosque", phonetic: "lah mohs-kay" },
            { french: "la synagogue", english: "synagogue", phonetic: "lah see-nah-gohg" },
            { french: "le temple", english: "temple", phonetic: "luh tahmpl" },
            { french: "le château", english: "castle", phonetic: "luh shah-toh" },
            { french: "le palais", english: "palace", phonetic: "luh pah-leh" },
            { french: "le monument", english: "monument", phonetic: "luh moh-noo-mahn" },
            { french: "la tour", english: "tower", phonetic: "lah toor" },
            { french: "le pont", english: "bridge", phonetic: "luh pohn" },
            { french: "la fontaine", english: "fountain", phonetic: "lah fohn-tehn" }
        ]
    },
    body: {
        name: "Body Parts",
        icon: "🫀",
        words: [
            { french: "le corps", english: "body", phonetic: "luh kohr" },
            { french: "la tête", english: "head", phonetic: "lah teht" },
            { french: "le visage", english: "face", phonetic: "luh vee-zahzh" },
            { french: "le front", english: "forehead", phonetic: "luh frohn" },
            { french: "les cheveux", english: "hair", phonetic: "lay shuh-vuh" },
            { french: "les yeux", english: "eyes", phonetic: "lay zyuh" },
            { french: "l'œil", english: "eye", phonetic: "luhy" },
            { french: "le sourcil", english: "eyebrow", phonetic: "luh soor-see" },
            { french: "le cil", english: "eyelash", phonetic: "luh seel" },
            { french: "la paupière", english: "eyelid", phonetic: "lah poh-pyehr" },
            { french: "le nez", english: "nose", phonetic: "luh nay" },
            { french: "la joue", english: "cheek", phonetic: "lah zhoo" },
            { french: "la bouche", english: "mouth", phonetic: "lah boosh" },
            { french: "les lèvres", english: "lips", phonetic: "lay lehvr" },
            { french: "les dents", english: "teeth", phonetic: "lay dahn" },
            { french: "la dent", english: "tooth", phonetic: "lah dahn" },
            { french: "la langue", english: "tongue", phonetic: "lah lahng" },
            { french: "le menton", english: "chin", phonetic: "luh mahn-tohn" },
            { french: "la mâchoire", english: "jaw", phonetic: "lah mah-shwahr" },
            { french: "l'oreille", english: "ear", phonetic: "loh-ray" },
            { french: "le cou", english: "neck", phonetic: "luh koo" },
            { french: "la gorge", english: "throat", phonetic: "lah gohrz" },
            { french: "l'épaule", english: "shoulder", phonetic: "lay-pohl" },
            { french: "le bras", english: "arm", phonetic: "luh brah" },
            { french: "le coude", english: "elbow", phonetic: "luh kood" },
            { french: "le poignet", english: "wrist", phonetic: "luh pwah-nyeh" },
            { french: "la main", english: "hand", phonetic: "lah mahn" },
            { french: "le doigt", english: "finger", phonetic: "luh dwah" },
            { french: "le pouce", english: "thumb", phonetic: "luh poos" },
            { french: "l'index", english: "index finger", phonetic: "lahn-dehks" },
            { french: "l'ongle", english: "nail", phonetic: "lohngl" },
            { french: "la paume", english: "palm", phonetic: "lah pohm" },
            { french: "le poing", english: "fist", phonetic: "luh pwahn" },
            { french: "la poitrine", english: "chest", phonetic: "lah pwah-treen" },
            { french: "le sein", english: "breast", phonetic: "luh sahn" },
            { french: "le dos", english: "back", phonetic: "luh doh" },
            { french: "la colonne vertébrale", english: "spine", phonetic: "lah koh-lohn vehr-tay-brahl" },
            { french: "le ventre", english: "stomach/belly", phonetic: "luh vahntr" },
            { french: "la taille", english: "waist", phonetic: "lah tahy" },
            { french: "la hanche", english: "hip", phonetic: "lah ahnsh" },
            { french: "les fesses", english: "buttocks", phonetic: "lay fehs" },
            { french: "la jambe", english: "leg", phonetic: "lah zhahmb" },
            { french: "la cuisse", english: "thigh", phonetic: "lah kwees" },
            { french: "le genou", english: "knee", phonetic: "luh zhuh-noo" },
            { french: "le mollet", english: "calf", phonetic: "luh moh-leh" },
            { french: "la cheville", english: "ankle", phonetic: "lah shuh-vee" },
            { french: "le pied", english: "foot", phonetic: "luh pyay" },
            { french: "le talon", english: "heel", phonetic: "luh tah-lohn" },
            { french: "l'orteil", english: "toe", phonetic: "lohr-tay" },
            { french: "la plante du pied", english: "sole of foot", phonetic: "lah plahnt doo pyay" },
            { french: "le cœur", english: "heart", phonetic: "luh kuhr" },
            { french: "le poumon", english: "lung", phonetic: "luh poo-mohn" },
            { french: "l'estomac", english: "stomach", phonetic: "lehs-toh-mah" },
            { french: "le foie", english: "liver", phonetic: "luh fwah" },
            { french: "le rein", english: "kidney", phonetic: "luh rahn" },
            { french: "le cerveau", english: "brain", phonetic: "luh sehr-voh" },
            { french: "l'os", english: "bone", phonetic: "lohs" },
            { french: "le muscle", english: "muscle", phonetic: "luh mooskl" },
            { french: "la peau", english: "skin", phonetic: "lah poh" },
            { french: "le sang", english: "blood", phonetic: "luh sahn" },
            { french: "la veine", english: "vein", phonetic: "lah vehn" },
            { french: "l'artère", english: "artery", phonetic: "lahr-tehr" },
            { french: "le nerf", english: "nerve", phonetic: "luh nehrf" }
        ]
    },
    clothing: {
        name: "Clothing & Fashion",
        icon: "👔",
        words: [
            { french: "les vêtements", english: "clothes", phonetic: "lay veht-mahn" },
            { french: "la mode", english: "fashion", phonetic: "lah mohd" },
            { french: "le style", english: "style", phonetic: "luh steel" },
            { french: "la chemise", english: "shirt", phonetic: "lah shuh-meez" },
            { french: "le chemisier", english: "blouse", phonetic: "luh shuh-mee-zyay" },
            { french: "le t-shirt", english: "t-shirt", phonetic: "luh tee-shuhrt" },
            { french: "le polo", english: "polo shirt", phonetic: "luh poh-loh" },
            { french: "le débardeur", english: "tank top", phonetic: "luh day-bahr-duhr" },
            { french: "le pull", english: "sweater", phonetic: "luh pool" },
            { french: "le pull-over", english: "pullover", phonetic: "luh pool-oh-vehr" },
            { french: "le sweat", english: "sweatshirt", phonetic: "luh sweht" },
            { french: "le sweat à capuche", english: "hoodie", phonetic: "luh sweht ah kah-poosh" },
            { french: "le gilet", english: "cardigan/vest", phonetic: "luh zhee-leh" },
            { french: "la veste", english: "jacket", phonetic: "lah vehst" },
            { french: "le blazer", english: "blazer", phonetic: "luh blah-zehr" },
            { french: "le manteau", english: "coat", phonetic: "luh mahn-toh" },
            { french: "l'imperméable", english: "raincoat", phonetic: "lahm-pehr-may-ahbl" },
            { french: "le blouson", english: "jacket (casual)", phonetic: "luh bloo-zohn" },
            { french: "la doudoune", english: "down jacket", phonetic: "lah doo-doon" },
            { french: "le costume", english: "suit", phonetic: "luh kohs-toom" },
            { french: "le smoking", english: "tuxedo", phonetic: "luh smoh-keeng" },
            { french: "le pantalon", english: "pants/trousers", phonetic: "luh pahn-tah-lohn" },
            { french: "le jean", english: "jeans", phonetic: "luh zheen" },
            { french: "le short", english: "shorts", phonetic: "luh shohrt" },
            { french: "le bermuda", english: "bermuda shorts", phonetic: "luh behr-moo-dah" },
            { french: "le jogging", english: "sweatpants", phonetic: "luh zhoh-geeng" },
            { french: "le legging", english: "leggings", phonetic: "luh leh-geeng" },
            { french: "la jupe", english: "skirt", phonetic: "lah zhoop" },
            { french: "la minijupe", english: "miniskirt", phonetic: "lah mee-nee-zhoop" },
            { french: "la robe", english: "dress", phonetic: "lah rohb" },
            { french: "la robe de soirée", english: "evening dress", phonetic: "lah rohb duh swah-ray" },
            { french: "la combinaison", english: "jumpsuit", phonetic: "lah kohm-bee-neh-zohn" },
            { french: "le pyjama", english: "pajamas", phonetic: "luh pee-zhah-mah" },
            { french: "la chemise de nuit", english: "nightgown", phonetic: "lah shuh-meez duh nwee" },
            { french: "le peignoir", english: "bathrobe", phonetic: "luh peh-nywahr" },
            { french: "les sous-vêtements", english: "underwear", phonetic: "lay soo-veht-mahn" },
            { french: "le slip", english: "briefs", phonetic: "luh sleep" },
            { french: "le caleçon", english: "boxers", phonetic: "luh kah-luh-sohn" },
            { french: "la culotte", english: "panties", phonetic: "lah koo-loht" },
            { french: "le soutien-gorge", english: "bra", phonetic: "luh soo-tyahn gohr-zhuh" },
            { french: "le maillot de corps", english: "undershirt", phonetic: "luh mah-yoh duh kohr" },
            { french: "le maillot de bain", english: "swimsuit", phonetic: "luh mah-yoh duh bahn" },
            { french: "le bikini", english: "bikini", phonetic: "luh bee-kee-nee" },
            { french: "les chaussures", english: "shoes", phonetic: "lay shoh-soor" },
            { french: "les baskets", english: "sneakers", phonetic: "lay bahs-keht" },
            { french: "les tennis", english: "tennis shoes", phonetic: "lay teh-nees" },
            { french: "les bottes", english: "boots", phonetic: "lay boht" },
            { french: "les bottines", english: "ankle boots", phonetic: "lay boh-teen" },
            { french: "les mocassins", english: "loafers", phonetic: "lay moh-kah-sahn" },
            { french: "les escarpins", english: "high heels", phonetic: "lay ehs-kahr-pahn" },
            { french: "les sandales", english: "sandals", phonetic: "lay sahn-dahl" },
            { french: "les tongs", english: "flip-flops", phonetic: "lay tohng" },
            { french: "les pantoufles", english: "slippers", phonetic: "lay pahn-toofl" },
            { french: "les chaussettes", english: "socks", phonetic: "lay shoh-seht" },
            { french: "les collants", english: "tights", phonetic: "lay koh-lahn" },
            { french: "le chapeau", english: "hat", phonetic: "luh shah-poh" },
            { french: "la casquette", english: "cap", phonetic: "lah kahs-keht" },
            { french: "le bonnet", english: "beanie", phonetic: "luh boh-neh" },
            { french: "le béret", english: "beret", phonetic: "luh bay-reh" },
            { french: "l'écharpe", english: "scarf", phonetic: "lay-shahrp" },
            { french: "le foulard", english: "scarf (light)", phonetic: "luh foo-lahr" },
            { french: "la cravate", english: "tie", phonetic: "lah krah-vaht" },
            { french: "le nœud papillon", english: "bow tie", phonetic: "luh nuh pah-pee-yohn" },
            { french: "les gants", english: "gloves", phonetic: "lay gahn" },
            { french: "les moufles", english: "mittens", phonetic: "lay moofl" },
            { french: "la ceinture", english: "belt", phonetic: "lah sehn-toor" },
            { french: "les bretelles", english: "suspenders", phonetic: "lay bruh-tehl" },
            { french: "le sac", english: "bag", phonetic: "luh sahk" },
            { french: "le sac à main", english: "handbag", phonetic: "luh sahk ah mahn" },
            { french: "le sac à dos", english: "backpack", phonetic: "luh sahk ah doh" },
            { french: "le portefeuille", english: "wallet", phonetic: "luh pohrt-fuhy" },
            { french: "le porte-monnaie", english: "coin purse", phonetic: "luh pohrt-moh-neh" },
            { french: "les lunettes", english: "glasses", phonetic: "lay loo-neht" },
            { french: "les lunettes de soleil", english: "sunglasses", phonetic: "lay loo-neht duh soh-lay" },
            { french: "le parapluie", english: "umbrella", phonetic: "luh pah-rah-ploo-ee" },
            { french: "la montre", english: "watch", phonetic: "lah mohntr" },
            { french: "le bijou", english: "jewel", phonetic: "luh bee-zhoo" },
            { french: "le collier", english: "necklace", phonetic: "luh koh-lyay" },
            { french: "le bracelet", english: "bracelet", phonetic: "luh brah-sleh" },
            { french: "la bague", english: "ring", phonetic: "lah bahg" },
            { french: "les boucles d'oreilles", english: "earrings", phonetic: "lay bookl doh-ray" },
            { french: "la taille", english: "size", phonetic: "lah tahy" },
            { french: "la pointure", english: "shoe size", phonetic: "lah pwahn-toor" },
            { french: "serré", english: "tight", phonetic: "seh-ray" },
            { french: "ample", english: "loose", phonetic: "ahmpl" }
        ]
    },
    weather: {
        name: "Weather & Climate",
        icon: "☀️",
        words: [
            { french: "le temps", english: "weather", phonetic: "luh tahn" },
            { french: "le climat", english: "climate", phonetic: "luh klee-mah" },
            { french: "la météo", english: "weather forecast", phonetic: "lah may-tay-oh" },
            { french: "la température", english: "temperature", phonetic: "lah tahn-pay-rah-toor" },
            { french: "le degré", english: "degree", phonetic: "luh duh-gray" },
            { french: "le soleil", english: "sun", phonetic: "luh soh-lay" },
            { french: "la lune", english: "moon", phonetic: "lah loon" },
            { french: "le ciel", english: "sky", phonetic: "luh syehl" },
            { french: "le nuage", english: "cloud", phonetic: "luh noo-ahzh" },
            { french: "la pluie", english: "rain", phonetic: "lah ploo-ee" },
            { french: "l'averse", english: "shower (rain)", phonetic: "lah-vehrs" },
            { french: "l'orage", english: "storm", phonetic: "loh-rahzh" },
            { french: "la tempête", english: "storm (big)", phonetic: "lah tahm-peht" },
            { french: "l'éclair", english: "lightning", phonetic: "lay-klehr" },
            { french: "le tonnerre", english: "thunder", phonetic: "luh toh-nehr" },
            { french: "la foudre", english: "lightning bolt", phonetic: "lah foodr" },
            { french: "la neige", english: "snow", phonetic: "lah nehzh" },
            { french: "le flocon de neige", english: "snowflake", phonetic: "luh floh-kohn duh nehzh" },
            { french: "la grêle", english: "hail", phonetic: "lah grehl" },
            { french: "le verglas", english: "black ice", phonetic: "luh vehr-glah" },
            { french: "le givre", english: "frost", phonetic: "luh zheevr" },
            { french: "la glace", english: "ice", phonetic: "lah glahs" },
            { french: "le brouillard", english: "fog", phonetic: "luh broo-yahr" },
            { french: "la brume", english: "mist", phonetic: "lah broom" },
            { french: "le vent", english: "wind", phonetic: "luh vahn" },
            { french: "la brise", english: "breeze", phonetic: "lah breez" },
            { french: "la rafale", english: "gust of wind", phonetic: "lah rah-fahl" },
            { french: "l'ouragan", english: "hurricane", phonetic: "loo-rah-gahn" },
            { french: "le cyclone", english: "cyclone", phonetic: "luh see-klohn" },
            { french: "la tornade", english: "tornado", phonetic: "lah tohr-nahd" },
            { french: "l'arc-en-ciel", english: "rainbow", phonetic: "lahrk-ahn-syehl" },
            { french: "l'humidité", english: "humidity", phonetic: "loo-mee-dee-tay" },
            { french: "la sécheresse", english: "drought", phonetic: "lah say-shuh-rehs" },
            { french: "l'inondation", english: "flood", phonetic: "lee-nohn-dah-syohn" },
            { french: "il fait beau", english: "it's nice weather", phonetic: "eel feh boh" },
            { french: "il fait mauvais", english: "it's bad weather", phonetic: "eel feh moh-veh" },
            { french: "il fait chaud", english: "it's hot", phonetic: "eel feh shoh" },
            { french: "il fait froid", english: "it's cold", phonetic: "eel feh frwah" },
            { french: "il fait frais", english: "it's cool", phonetic: "eel feh freh" },
            { french: "il fait doux", english: "it's mild", phonetic: "eel feh doo" },
            { french: "il pleut", english: "it's raining", phonetic: "eel pluh" },
            { french: "il neige", english: "it's snowing", phonetic: "eel nehzh" },
            { french: "il fait du vent", english: "it's windy", phonetic: "eel feh doo vahn" },
            { french: "il fait du brouillard", english: "it's foggy", phonetic: "eel feh doo broo-yahr" },
            { french: "il fait du soleil", english: "it's sunny", phonetic: "eel feh doo soh-lay" },
            { french: "il y a des nuages", english: "it's cloudy", phonetic: "eel yah day noo-ahzh" },
            { french: "ensoleillé", english: "sunny", phonetic: "ahn-soh-lay-yay" },
            { french: "nuageux", english: "cloudy", phonetic: "noo-ah-zhuh" },
            { french: "couvert", english: "overcast", phonetic: "koo-vehr" },
            { french: "pluvieux", english: "rainy", phonetic: "ploo-vyuh" },
            { french: "orageux", english: "stormy", phonetic: "oh-rah-zhuh" },
            { french: "humide", english: "humid", phonetic: "oo-meed" },
            { french: "sec", english: "dry", phonetic: "sehk" },
            { french: "glacial", english: "freezing", phonetic: "glah-syahl" }
        ]
    },
    work: {
        name: "Work & Professions",
        icon: "💼",
        words: [
            { french: "le travail", english: "work/job", phonetic: "luh trah-vahy" },
            { french: "l'emploi", english: "employment/job", phonetic: "lahm-plwah" },
            { french: "le métier", english: "profession/trade", phonetic: "luh may-tyay" },
            { french: "la carrière", english: "career", phonetic: "lah kah-ryehr" },
            { french: "le bureau", english: "office", phonetic: "luh boo-roh" },
            { french: "l'entreprise", english: "company", phonetic: "lahn-truh-preez" },
            { french: "le patron/la patronne", english: "boss", phonetic: "luh pah-trohn" },
            { french: "le/la collègue", english: "colleague", phonetic: "luh/lah koh-lehg" },
            { french: "l'employé(e)", english: "employee", phonetic: "lahm-plwah-yay" },
            { french: "le salaire", english: "salary", phonetic: "luh sah-lehr" },
            { french: "la réunion", english: "meeting", phonetic: "lah ray-oo-nyohn" },
            { french: "le CV", english: "resume/CV", phonetic: "luh say-vay" },
            { french: "l'entretien", english: "interview", phonetic: "lahn-truh-tyahn" },
            { french: "le médecin", english: "doctor", phonetic: "luh mayd-sahn" },
            { french: "l'avocat(e)", english: "lawyer", phonetic: "lah-voh-kah" },
            { french: "le professeur", english: "teacher", phonetic: "luh proh-feh-suhr" },
            { french: "l'ingénieur", english: "engineer", phonetic: "lahn-zhay-nyuhr" },
            { french: "le/la comptable", english: "accountant", phonetic: "luh/lah kohn-tahbl" },
            { french: "l'homme/la femme d'affaires", english: "businessman/woman", phonetic: "lohm/lah fahm dah-fehr" },
            { french: "le/la secrétaire", english: "secretary", phonetic: "luh/lah suh-kray-tehr" },
            { french: "le vendeur/la vendeuse", english: "salesperson", phonetic: "luh vahn-duhr/lah vahn-duhz" },
            { french: "le serveur/la serveuse", english: "waiter/waitress", phonetic: "luh sehr-vuhr/lah sehr-vuhz" },
            { french: "le cuisinier/la cuisinière", english: "cook", phonetic: "luh kwee-zee-nyay" },
            { french: "le boulanger/la boulangère", english: "baker", phonetic: "luh boo-lahn-zhay" },
            { french: "le boucher/la bouchère", english: "butcher", phonetic: "luh boo-shay" },
            { french: "le coiffeur/la coiffeuse", english: "hairdresser", phonetic: "luh kwah-fuhr" },
            { french: "le plombier", english: "plumber", phonetic: "luh plohm-byay" },
            { french: "l'électricien(ne)", english: "electrician", phonetic: "lay-lehk-tree-syahn" },
            { french: "le mécanicien", english: "mechanic", phonetic: "luh may-kah-nee-syahn" },
            { french: "le chauffeur", english: "driver", phonetic: "luh shoh-fuhr" },
            { french: "le pilote", english: "pilot", phonetic: "luh pee-loht" },
            { french: "le policier/la policière", english: "police officer", phonetic: "luh poh-lee-syay" },
            { french: "le pompier", english: "firefighter", phonetic: "luh pohm-pyay" },
            { french: "le soldat", english: "soldier", phonetic: "luh sohl-dah" },
            { french: "le/la journaliste", english: "journalist", phonetic: "luh/lah zhoor-nah-leest" },
            { french: "l'écrivain(e)", english: "writer", phonetic: "lay-kree-vahn" },
            { french: "le/la photographe", english: "photographer", phonetic: "luh/lah foh-toh-grahf" },
            { french: "l'acteur/l'actrice", english: "actor/actress", phonetic: "lahk-tuhr/lahk-trees" },
            { french: "le chanteur/la chanteuse", english: "singer", phonetic: "luh shahn-tuhr" },
            { french: "le musicien/la musicienne", english: "musician", phonetic: "luh moo-zee-syahn" },
            { french: "le/la peintre", english: "painter", phonetic: "luh/lah pahntr" },
            { french: "l'agriculteur/l'agricultrice", english: "farmer", phonetic: "lah-gree-kool-tuhr" },
            { french: "le jardinier/la jardinière", english: "gardener", phonetic: "luh zhahr-dee-nyay" },
            { french: "le programmeur/la programmeuse", english: "programmer", phonetic: "luh proh-grah-muhr" },
            { french: "l'informaticien(ne)", english: "IT specialist", phonetic: "lahn-fohr-mah-tee-syahn" }
        ]
    },
    emotions: {
        name: "Emotions & Feelings",
        icon: "😊",
        words: [
            { french: "le sentiment", english: "feeling", phonetic: "luh sahn-tee-mahn" },
            { french: "l'émotion", english: "emotion", phonetic: "lay-moh-syohn" },
            { french: "l'humeur", english: "mood", phonetic: "loo-muhr" },
            { french: "heureux/heureuse", english: "happy", phonetic: "uh-ruh/uh-ruhz" },
            { french: "content(e)", english: "pleased/glad", phonetic: "kohn-tahn(t)" },
            { french: "joyeux/joyeuse", english: "joyful", phonetic: "zhwah-yuh/zhwah-yuhz" },
            { french: "ravi(e)", english: "delighted", phonetic: "rah-vee" },
            { french: "enchanté(e)", english: "delighted", phonetic: "ahn-shahn-tay" },
            { french: "satisfait(e)", english: "satisfied", phonetic: "sah-tees-feh(t)" },
            { french: "fier/fière", english: "proud", phonetic: "fyehr" },
            { french: "soulagé(e)", english: "relieved", phonetic: "soo-lah-zhay" },
            { french: "reconnaissant(e)", english: "grateful", phonetic: "ruh-koh-neh-sahn(t)" },
            { french: "amoureux/amoureuse", english: "in love", phonetic: "ah-moo-ruh/ah-moo-ruhz" },
            { french: "passionné(e)", english: "passionate", phonetic: "pah-syoh-nay" },
            { french: "excité(e)", english: "excited", phonetic: "ehk-see-tay" },
            { french: "enthousiaste", english: "enthusiastic", phonetic: "ahn-too-zyahst" },
            { french: "optimiste", english: "optimistic", phonetic: "ohp-tee-meest" },
            { french: "confiant(e)", english: "confident", phonetic: "kohn-fyahn(t)" },
            { french: "calme", english: "calm", phonetic: "kahlm" },
            { french: "serein(e)", english: "serene", phonetic: "suh-rahn" },
            { french: "détendu(e)", english: "relaxed", phonetic: "day-tahn-doo" },
            { french: "tranquille", english: "peaceful", phonetic: "trahn-keel" },
            { french: "triste", english: "sad", phonetic: "treest" },
            { french: "malheureux/malheureuse", english: "unhappy", phonetic: "mah-luh-ruh" },
            { french: "déprimé(e)", english: "depressed", phonetic: "day-pree-may" },
            { french: "découragé(e)", english: "discouraged", phonetic: "day-koo-rah-zhay" },
            { french: "déçu(e)", english: "disappointed", phonetic: "day-soo" },
            { french: "nostalgique", english: "nostalgic", phonetic: "nohs-tahl-zheek" },
            { french: "mélancolique", english: "melancholic", phonetic: "may-lahn-koh-leek" },
            { french: "en colère", english: "angry", phonetic: "ahn koh-lehr" },
            { french: "fâché(e)", english: "angry/upset", phonetic: "fah-shay" },
            { french: "furieux/furieuse", english: "furious", phonetic: "foo-ryuh/foo-ryuhz" },
            { french: "énervé(e)", english: "annoyed", phonetic: "ay-nehr-vay" },
            { french: "agacé(e)", english: "irritated", phonetic: "ah-gah-say" },
            { french: "frustré(e)", english: "frustrated", phonetic: "froos-tray" },
            { french: "jaloux/jalouse", english: "jealous", phonetic: "zhah-loo/zhah-looz" },
            { french: "envieux/envieuse", english: "envious", phonetic: "ahn-vyuh/ahn-vyuhz" },
            { french: "inquiet/inquiète", english: "worried", phonetic: "ahn-kyeh/ahn-kyeht" },
            { french: "anxieux/anxieuse", english: "anxious", phonetic: "ahnk-syuh/ahnk-syuhz" },
            { french: "stressé(e)", english: "stressed", phonetic: "streh-say" },
            { french: "nerveux/nerveuse", english: "nervous", phonetic: "nehr-vuh/nehr-vuhz" },
            { french: "tendu(e)", english: "tense", phonetic: "tahn-doo" },
            { french: "effrayé(e)", english: "frightened", phonetic: "eh-freh-yay" },
            { french: "terrifié(e)", english: "terrified", phonetic: "teh-ree-fyay" },
            { french: "paniqué(e)", english: "panicked", phonetic: "pah-nee-kay" },
            { french: "choqué(e)", english: "shocked", phonetic: "shoh-kay" },
            { french: "surpris(e)", english: "surprised", phonetic: "soor-pree(z)" },
            { french: "étonné(e)", english: "astonished", phonetic: "ay-toh-nay" },
            { french: "confus(e)", english: "confused", phonetic: "kohn-foo(z)" },
            { french: "perplexe", english: "puzzled", phonetic: "pehr-plehks" },
            { french: "fatigué(e)", english: "tired", phonetic: "fah-tee-gay" },
            { french: "épuisé(e)", english: "exhausted", phonetic: "ay-pwee-zay" },
            { french: "ennuyé(e)", english: "bored", phonetic: "ahn-nwee-yay" },
            { french: "gêné(e)", english: "embarrassed", phonetic: "zheh-nay" },
            { french: "honteux/honteuse", english: "ashamed", phonetic: "ohn-tuh/ohn-tuhz" },
            { french: "coupable", english: "guilty", phonetic: "koo-pahbl" },
            { french: "seul(e)", english: "lonely", phonetic: "suhl" },
            { french: "indifférent(e)", english: "indifferent", phonetic: "ahn-dee-fay-rahn(t)" },
            { french: "pessimiste", english: "pessimistic", phonetic: "peh-see-meest" }
        ]
    },
    nature: {
        name: "Nature & Environment",
        icon: "🌿",
        words: [
            { french: "la nature", english: "nature", phonetic: "lah nah-toor" },
            { french: "l'environnement", english: "environment", phonetic: "lahn-vee-rohn-mahn" },
            { french: "le paysage", english: "landscape", phonetic: "luh pay-ee-zahzh" },
            { french: "la terre", english: "earth/land", phonetic: "lah tehr" },
            { french: "le sol", english: "ground/soil", phonetic: "luh sohl" },
            { french: "la montagne", english: "mountain", phonetic: "lah mohn-tahn-yuh" },
            { french: "la colline", english: "hill", phonetic: "lah koh-leen" },
            { french: "la vallée", english: "valley", phonetic: "lah vah-lay" },
            { french: "la plaine", english: "plain", phonetic: "lah plehn" },
            { french: "le plateau", english: "plateau", phonetic: "luh plah-toh" },
            { french: "la falaise", english: "cliff", phonetic: "lah fah-lehz" },
            { french: "le rocher", english: "rock", phonetic: "luh roh-shay" },
            { french: "la pierre", english: "stone", phonetic: "lah pyehr" },
            { french: "le sable", english: "sand", phonetic: "luh sahbl" },
            { french: "la forêt", english: "forest", phonetic: "lah foh-reh" },
            { french: "le bois", english: "wood/woods", phonetic: "luh bwah" },
            { french: "la jungle", english: "jungle", phonetic: "lah zhungl" },
            { french: "l'arbre", english: "tree", phonetic: "lahrbr" },
            { french: "le chêne", english: "oak", phonetic: "luh shehn" },
            { french: "le pin", english: "pine", phonetic: "luh pahn" },
            { french: "le sapin", english: "fir tree", phonetic: "luh sah-pahn" },
            { french: "le palmier", english: "palm tree", phonetic: "luh pahl-myay" },
            { french: "la branche", english: "branch", phonetic: "lah brahnsh" },
            { french: "le tronc", english: "trunk", phonetic: "luh trohnk" },
            { french: "la racine", english: "root", phonetic: "lah rah-seen" },
            { french: "la feuille", english: "leaf", phonetic: "lah fuhy" },
            { french: "l'écorce", english: "bark", phonetic: "lay-kohrs" },
            { french: "la fleur", english: "flower", phonetic: "lah fluhr" },
            { french: "la rose", english: "rose", phonetic: "lah rohz" },
            { french: "le tournesol", english: "sunflower", phonetic: "luh toor-nuh-sohl" },
            { french: "la tulipe", english: "tulip", phonetic: "lah too-leep" },
            { french: "le lys", english: "lily", phonetic: "luh lees" },
            { french: "la marguerite", english: "daisy", phonetic: "lah mahr-guh-reet" },
            { french: "l'herbe", english: "grass", phonetic: "lehrb" },
            { french: "la pelouse", english: "lawn", phonetic: "lah puh-looz" },
            { french: "le buisson", english: "bush", phonetic: "luh bwee-sohn" },
            { french: "la plante", english: "plant", phonetic: "lah plahnt" },
            { french: "la graine", english: "seed", phonetic: "lah grehn" },
            { french: "l'eau", english: "water", phonetic: "loh" },
            { french: "la mer", english: "sea", phonetic: "lah mehr" },
            { french: "l'océan", english: "ocean", phonetic: "loh-say-ahn" },
            { french: "la plage", english: "beach", phonetic: "lah plahzh" },
            { french: "la côte", english: "coast", phonetic: "lah koht" },
            { french: "l'île", english: "island", phonetic: "leel" },
            { french: "la vague", english: "wave", phonetic: "lah vahg" },
            { french: "la marée", english: "tide", phonetic: "lah mah-ray" },
            { french: "le lac", english: "lake", phonetic: "luh lahk" },
            { french: "l'étang", english: "pond", phonetic: "lay-tahng" },
            { french: "la rivière", english: "river", phonetic: "lah ree-vyehr" },
            { french: "le fleuve", english: "large river", phonetic: "luh fluhv" },
            { french: "le ruisseau", english: "stream", phonetic: "luh rwee-soh" },
            { french: "la cascade", english: "waterfall", phonetic: "lah kahs-kahd" },
            { french: "la source", english: "spring (water)", phonetic: "lah soors" },
            { french: "le désert", english: "desert", phonetic: "luh day-zehr" },
            { french: "l'air", english: "air", phonetic: "lehr" },
            { french: "le feu", english: "fire", phonetic: "luh fuh" },
            { french: "la flamme", english: "flame", phonetic: "lah flahm" },
            { french: "la fumée", english: "smoke", phonetic: "lah foo-may" },
            { french: "le ciel", english: "sky", phonetic: "luh syehl" },
            { french: "l'étoile", english: "star", phonetic: "lay-twahl" },
            { french: "la lune", english: "moon", phonetic: "lah loon" },
            { french: "le soleil", english: "sun", phonetic: "luh soh-lay" },
            { french: "l'horizon", english: "horizon", phonetic: "loh-ree-zohn" },
            { french: "le lever du soleil", english: "sunrise", phonetic: "luh luh-vay doo soh-lay" },
            { french: "le coucher du soleil", english: "sunset", phonetic: "luh koo-shay doo soh-lay" }
        ]
    },
    animals: {
        name: "Animals",
        icon: "🦁",
        words: [
            { french: "l'animal", english: "animal", phonetic: "lah-nee-mahl" },
            { french: "le chien", english: "dog", phonetic: "luh shyahn" },
            { french: "le chat", english: "cat", phonetic: "luh shah" },
            { french: "le chiot", english: "puppy", phonetic: "luh shyoh" },
            { french: "le chaton", english: "kitten", phonetic: "luh shah-tohn" },
            { french: "l'oiseau", english: "bird", phonetic: "lwah-zoh" },
            { french: "le poisson", english: "fish", phonetic: "luh pwah-sohn" },
            { french: "le poisson rouge", english: "goldfish", phonetic: "luh pwah-sohn roozh" },
            { french: "le lapin", english: "rabbit", phonetic: "luh lah-pahn" },
            { french: "le hamster", english: "hamster", phonetic: "luh ahm-stehr" },
            { french: "la souris", english: "mouse", phonetic: "lah soo-ree" },
            { french: "le rat", english: "rat", phonetic: "luh rah" },
            { french: "le cochon d'Inde", english: "guinea pig", phonetic: "luh koh-shohn dahnd" },
            { french: "la tortue", english: "turtle", phonetic: "lah tohr-too" },
            { french: "le cheval", english: "horse", phonetic: "luh shuh-vahl" },
            { french: "la jument", english: "mare", phonetic: "lah zhoo-mahn" },
            { french: "le poulain", english: "foal", phonetic: "luh poo-lahn" },
            { french: "l'âne", english: "donkey", phonetic: "lahn" },
            { french: "la vache", english: "cow", phonetic: "lah vahsh" },
            { french: "le taureau", english: "bull", phonetic: "luh toh-roh" },
            { french: "le veau", english: "calf", phonetic: "luh voh" },
            { french: "le cochon", english: "pig", phonetic: "luh koh-shohn" },
            { french: "le mouton", english: "sheep", phonetic: "luh moo-tohn" },
            { french: "l'agneau", english: "lamb", phonetic: "lah-nyoh" },
            { french: "la chèvre", english: "goat", phonetic: "lah shehvr" },
            { french: "le coq", english: "rooster", phonetic: "luh kohk" },
            { french: "la poule", english: "hen", phonetic: "lah pool" },
            { french: "le poulet", english: "chicken", phonetic: "luh poo-leh" },
            { french: "le poussin", english: "chick", phonetic: "luh poo-sahn" },
            { french: "le canard", english: "duck", phonetic: "luh kah-nahr" },
            { french: "l'oie", english: "goose", phonetic: "lwah" },
            { french: "la dinde", english: "turkey", phonetic: "lah dahnd" },
            { french: "le lion", english: "lion", phonetic: "luh lyohn" },
            { french: "la lionne", english: "lioness", phonetic: "lah lyohn" },
            { french: "le tigre", english: "tiger", phonetic: "luh teegr" },
            { french: "l'éléphant", english: "elephant", phonetic: "lay-lay-fahn" },
            { french: "la girafe", english: "giraffe", phonetic: "lah zhee-rahf" },
            { french: "le singe", english: "monkey", phonetic: "luh sahnzh" },
            { french: "le gorille", english: "gorilla", phonetic: "luh goh-ree" },
            { french: "l'ours", english: "bear", phonetic: "loors" },
            { french: "le loup", english: "wolf", phonetic: "luh loo" },
            { french: "le renard", english: "fox", phonetic: "luh ruh-nahr" },
            { french: "le cerf", english: "deer", phonetic: "luh sehr" },
            { french: "le sanglier", english: "wild boar", phonetic: "luh sahn-glyay" },
            { french: "l'écureuil", english: "squirrel", phonetic: "lay-koo-ruhy" },
            { french: "le hérisson", english: "hedgehog", phonetic: "luh ay-ree-sohn" },
            { french: "la chauve-souris", english: "bat", phonetic: "lah shohv-soo-ree" },
            { french: "le serpent", english: "snake", phonetic: "luh sehr-pahn" },
            { french: "le crocodile", english: "crocodile", phonetic: "luh kroh-koh-deel" },
            { french: "le lézard", english: "lizard", phonetic: "luh lay-zahr" },
            { french: "la grenouille", english: "frog", phonetic: "lah gruh-noo-ee" },
            { french: "le dauphin", english: "dolphin", phonetic: "luh doh-fahn" },
            { french: "la baleine", english: "whale", phonetic: "lah bah-lehn" },
            { french: "le requin", english: "shark", phonetic: "luh ruh-kahn" },
            { french: "le phoque", english: "seal", phonetic: "luh fohk" },
            { french: "le pingouin", english: "penguin", phonetic: "luh pahn-gwahn" },
            { french: "l'aigle", english: "eagle", phonetic: "lehgl" },
            { french: "le hibou", english: "owl", phonetic: "luh ee-boo" },
            { french: "le corbeau", english: "crow", phonetic: "luh kohr-boh" },
            { french: "le pigeon", english: "pigeon", phonetic: "luh pee-zhohn" },
            { french: "le moineau", english: "sparrow", phonetic: "luh mwah-noh" },
            { french: "l'hirondelle", english: "swallow", phonetic: "lee-rohn-dehl" },
            { french: "le papillon", english: "butterfly", phonetic: "luh pah-pee-yohn" },
            { french: "l'abeille", english: "bee", phonetic: "lah-behy" },
            { french: "la guêpe", english: "wasp", phonetic: "lah gehp" },
            { french: "la mouche", english: "fly", phonetic: "lah moosh" },
            { french: "le moustique", english: "mosquito", phonetic: "luh moos-teek" },
            { french: "l'araignée", english: "spider", phonetic: "lah-reh-nyay" },
            { french: "la fourmi", english: "ant", phonetic: "lah foor-mee" },
            { french: "le scarabée", english: "beetle", phonetic: "luh skah-rah-bay" },
            { french: "la coccinelle", english: "ladybug", phonetic: "lah kohk-see-nehl" },
            { french: "l'escargot", english: "snail", phonetic: "lehs-kahr-goh" },
            { french: "le ver", english: "worm", phonetic: "luh vehr" }
        ]
    },
}

// Get all category names
function getVocabularyCategories() {
    return Object.keys(FRENCH_VOCABULARY).map(key => ({
        key: key,
        name: FRENCH_VOCABULARY[key].name,
        icon: FRENCH_VOCABULARY[key].icon,
        count: FRENCH_VOCABULARY[key].words.length
    }));
}
